# Final evaluation launcher — selected heuristics + external baselines

This notebook launches the **final thesis evaluation only**. It does **not** call the LLM, does **not** generate new heuristics, and does **not** modify the LLM loop pipeline.

Recommended workflow:

1. Edit the control panel.
2. Mount Drive.
3. Install only the final-evaluation dependencies.
4. Build a temporary runtime config.
5. Run a dry run.
6. Run a tiny smoke test.
7. Launch the full resumable evaluation.
8. Use the progress cells to monitor, stop, and resume.

## 1. Control panel

In [27]:
# ============================================================
# FINAL EVALUATION CONTROL PANEL
# ============================================================

# -------------------------
# Repo / runtime
# -------------------------
ORG = "TM-HESSO-202526"
REPO = "llm-clustering-heuristics"
BRANCH = "main"
USE_GITHUB_TOKEN = False
REFRESH_REPO_FROM_GITHUB = True   # Set True if you want Colab to clone a fresh copy.

# -------------------------
# Drive paths
# -------------------------
TM_DIR = "/content/drive/MyDrive/TM"
CLUSTER_ZIP_PATH = f"{TM_DIR}/cluster_tai.zip"

# Put Prof. Taillard's C++ zip or .cpp here. The runner compiles it with g++ -O2.
TAILLARD_CPP_SOURCE_PATH = "external/taillard_cpp/clustering_sphere.cpp"

# Optional references. Set to None if missing; raw objective values will still be reported.
SSE_REFERENCE_PATH = f"{TM_DIR}/kmeans.res"
PMEDIAN_REFERENCE_PATH = f"{TM_DIR}/kmeans.res"
RADIUS_FREE_REFERENCE_PATH = None
RADIUS_DATA_POINT_REFERENCE_PATH = f"{TM_DIR}/generator_radius_reference_last_p.zip"

ARTIFACT_DIR = f"{TM_DIR}/final-clustering-evaluation/final_eval_smoke_clean_v1"
INSTANCE_EXTRACT_DIR = "/content/final_eval_cluster_tai_extract"

# -------------------------
# Evaluation scope
# -------------------------
OBJECTIVES = ["sse", "pmedian", "radius"]
D_VALUES = [2]
P_VALUES = [20]
INSTANCE_IDS = [0]

# -------------------------
# Statistical protocol
# -------------------------
REPETITIONS = 1
TIMEOUT_S = 120
GLOBAL_SEED = 12345
CHECKPOINT_EVERY = 1
RESUME = False

# -------------------------
# Debug / launch controls
# -------------------------
DRY_RUN = False
SMOKE_TEST = False              # True = override to a tiny, fast test.
STOP_AFTER_JOBS = None         # Example: 20 to test resumability, None for no artificial stop.

# Smoke-test override. Used only when SMOKE_TEST=True.
SMOKE_OBJECTIVES = ["sse", "pmedian", "radius"]
SMOKE_D_VALUES = [2]
SMOKE_P_VALUES = [20]
SMOKE_INSTANCE_IDS = [0]
SMOKE_REPETITIONS = 1
SMOKE_TIMEOUT_S = 60

## 2. Mount Google Drive

In [28]:
from google.colab import drive

drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 3. Clone/enter repo and install final-evaluation dependencies

In [29]:
import importlib.util
import subprocess
import sys
from pathlib import Path
from getpass import getpass

repo_dir = Path(f"/content/{REPO}")

if REFRESH_REPO_FROM_GITHUB:
    if USE_GITHUB_TOKEN:
        token = getpass("Paste GitHub token with read access: ")
        repo_url = f"https://x-access-token:{token}@github.com/{ORG}/{REPO}.git"
    else:
        repo_url = f"https://github.com/{ORG}/{REPO}.git"

    %cd /content
    !rm -rf "{repo_dir}"
    !git clone --branch "{BRANCH}" "{repo_url}" "{repo_dir}"
    if USE_GITHUB_TOKEN:
        !git -C "{repo_dir}" remote set-url origin "https://github.com/{ORG}/{REPO}.git"
        del token
        del repo_url
else:
    # If this notebook is launched from a copied repo, use that repo.
    if not repo_dir.exists():
        print(f"{repo_dir} does not exist yet. Set REFRESH_REPO_FROM_GITHUB=True or unzip the repo to /content.")

%cd "{repo_dir}"
REPO_DIR = Path.cwd()
SRC_DIR = REPO_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

# Install the repo itself without dependency upgrades, following the main launcher pattern.
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "--no-deps", "-e", "."], check=True)

# Install only missing final-eval dependencies when possible. Some packages may already be in Colab.
required_modules = {
    "numpy": "numpy",
    "pandas": "pandas",
    "yaml": "PyYAML",
    "sklearn": "scikit-learn",
    "matplotlib": "matplotlib",
}
missing = [pkg for module, pkg in required_modules.items() if importlib.util.find_spec(module) is None]
# Optional but normally needed for p-median baselines.
if importlib.util.find_spec("kmedoids") is None:
    missing.append("kmedoids")
if importlib.util.find_spec("sklearn_extra") is None:
    missing.append("scikit-learn-extra")

if missing:
    print("Installing missing packages:", missing)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", *missing], check=True)
else:
    print("All final-evaluation dependencies appear available.")

# Check C++ compiler for Taillard baselines.
subprocess.run(["g++", "--version"], check=False)

/content
Cloning into '/content/llm-clustering-heuristics'...
remote: Enumerating objects: 531, done.
remote: Counting objects: 100% (531/531), done.
remote: Compressing objects: 100% (362/362), done.
remote: Total 531 (delta 265), reused 417 (delta 151), pack-reused 0 (from 0)
Receiving objects: 100% (531/531), 346.29 KiB | 11.17 MiB/s, done.
Resolving deltas: 100% (265/265), done.
/content/llm-clustering-heuristics
All final-evaluation dependencies appear available.

CompletedProcess(args=['g++', '--version'], returncode=0)

## 4. Build temporary runtime config from the control panel

In [30]:
import yaml
from pathlib import Path

REPO_DIR = Path.cwd()
base_cfg_path = REPO_DIR / "configs" / "final_eval.yaml"
with open(base_cfg_path, "r", encoding="utf-8") as f:
    cfg = yaml.safe_load(f)

objectives = SMOKE_OBJECTIVES if SMOKE_TEST else OBJECTIVES
d_values = SMOKE_D_VALUES if SMOKE_TEST else D_VALUES
p_values = SMOKE_P_VALUES if SMOKE_TEST else P_VALUES
instance_ids = SMOKE_INSTANCE_IDS if SMOKE_TEST else INSTANCE_IDS
reps = SMOKE_REPETITIONS if SMOKE_TEST else REPETITIONS
timeout_s = SMOKE_TIMEOUT_S if SMOKE_TEST else TIMEOUT_S

cfg["cluster_zip_path"] = CLUSTER_ZIP_PATH
cfg["selected_heuristics_dir"] = "experiments/selected_clustering_heuristics_final_by_objective"
cfg["artifact_dir"] = ARTIFACT_DIR + ("_smoke" if SMOKE_TEST else "")
cfg["instance_extract_dir"] = INSTANCE_EXTRACT_DIR
cfg["objectives"] = objectives
cfg["instance_filters"] = {
    "d_values": d_values,
    "p_values": p_values,
    "instance_ids": instance_ids,
    "min_n": None,
    "max_n": None,
}
cfg["repetitions"] = reps
cfg["timeout_s"] = timeout_s
cfg["global_seed"] = GLOBAL_SEED
cfg["resume"] = RESUME
cfg["checkpoint_every"] = CHECKPOINT_EVERY
cfg["taillard_cpp"]["source_path"] = TAILLARD_CPP_SOURCE_PATH

cfg["reference_tables"] = {
    "sse": SSE_REFERENCE_PATH,
    "pmedian": PMEDIAN_REFERENCE_PATH,
    # Run C free-center and data-point-center references are intentionally separate.
    "radius_free": RADIUS_FREE_REFERENCE_PATH,
    "radius_data_point": RADIUS_DATA_POINT_REFERENCE_PATH,
    "radius": None,
}

# If you set a reference path to None in the control panel, keep it as null in YAML.
for k, v in list(cfg["reference_tables"].items()):
    if v is None or str(v).strip().lower() in {"", "none", "null"}:
        cfg["reference_tables"][k] = None

runtime_cfg_path = REPO_DIR / "configs" / "final_eval_runtime.yaml"
with open(runtime_cfg_path, "w", encoding="utf-8") as f:
    yaml.safe_dump(cfg, f, sort_keys=False, allow_unicode=True)

print("Runtime config:", runtime_cfg_path)
print("Artifact dir:", cfg["artifact_dir"])
print("Objectives:", cfg["objectives"])
print("Instance filters:", cfg["instance_filters"])
print("Repetitions:", cfg["repetitions"])
print("Timeout per job:", cfg["timeout_s"])
print("Taillard C++ source:", cfg["taillard_cpp"]["source_path"])

Runtime config: /content/llm-clustering-heuristics/configs/final_eval_runtime.yaml
Artifact dir: /content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1
Objectives: ['sse', 'pmedian', 'radius']
Instance filters: {'d_values': [2], 'p_values': [20], 'instance_ids': [0], 'min_n': None, 'max_n': None}
Repetitions: 1
Timeout per job: 120
Taillard C++ source: external/taillard_cpp/clustering_sphere.cpp

## Evaluation transparency checks

These cells make the final-evaluation launcher explicit before anything expensive runs.

They show:

- where selected LLM heuristics are loaded from,
- which selected LLM heuristic files exist in the cloned repo,
- which external baselines are enabled in the runtime config,
- which methods were actually loaded by the runner after launch,
- current progress / last checkpointed jobs.

Important: `experiments/selected_clustering_heuristics_final_by_objective/` is **repo content**, not Google Drive content.  
It should resolve to `/content/llm-clustering-heuristics/experiments/selected_clustering_heuristics_final_by_objective/` after cloning the repo.

In [31]:
from pathlib import Path
import yaml
import pandas as pd
from IPython.display import display

runtime_config_path = REPO_DIR / "configs" / "final_eval_runtime.yaml"

print("=== RUNTIME CONFIG / PATHS ===")
print("REPO_DIR:", REPO_DIR)
print("Runtime config:", runtime_config_path)
print("Runtime config exists:", runtime_config_path.exists())

if not runtime_config_path.exists():
    raise FileNotFoundError(
        f"Runtime config not found: {runtime_config_path}\n"
        "Run the config-building cell before this transparency check."
    )

with open(runtime_config_path, "r") as f:
    cfg = yaml.safe_load(f)

print("\n=== ACTIVE FINAL EVALUATION CONFIG ===")
print("Objectives:", cfg.get("objectives"))
print("Repetitions:", cfg.get("repetitions"))
print("Timeout:", cfg.get("timeout_s"))
print("Artifact dir:", cfg.get("artifact_dir"))
print("Cluster zip path:", cfg.get("cluster_zip_path"))
print("Taillard C++ source path:", (cfg.get("taillard_cpp") or {}).get("source_path"))
print("Selected heuristics dir, as configured:", cfg.get("selected_heuristics_dir"))
print("Reference tables:", cfg.get("reference_tables"))

print("\n=== INSTANCE FILTERS ===")
print(cfg.get("instance_filters"))

selected_dir = REPO_DIR / cfg.get(
    "selected_heuristics_dir",
    "experiments/selected_clustering_heuristics_final_by_objective"
)

print("\n=== SELECTED LLM HEURISTICS SOURCE ===")
print("Resolved local path:", selected_dir)
print("Exists:", selected_dir.exists())

if not selected_dir.exists():
    raise FileNotFoundError(
        f"Selected heuristics folder not found: {selected_dir}\n"
        "This folder is expected inside the cloned GitHub repo."
    )

objective_folders = {
    "sse_free": ("sse", "free", "SSE_free_centers"),
    "pmedian_data_point": ("pmedian", "snap_to_points", "P_MEDIAN_data_point_centers"),
    "radius_free": ("radius", "free", "RADIUS_VOLUME_free_centers"),
    "radius_data_point": ("radius", "snap_to_points", "RADIUS_VOLUME_data_point_centers"),
}

heuristic_rows = []

for variant, (objective, center_constraint, folder_name) in objective_folders.items():
    folder = selected_dir / folder_name
    py_files = sorted(folder.rglob("*.py")) if folder.exists() else []

    print(f"\n{variant} -> {folder}")
    print("objective:", objective, "| center_constraint:", center_constraint)
    print("exists:", folder.exists(), "| python files:", len(py_files))

    for py in py_files:
        info = py.parent / "INFO.txt"
        source_row = py.parent / "source_row.json"
        heuristic_rows.append({
            "type": "llm_selected",
            "objective": objective,
            "variant": variant,
            "center_constraint": center_constraint,
            "method_folder": py.parent.name,
            "python_file": py.name,
            "has_info_txt": info.exists(),
            "has_source_row_json": source_row.exists(),
            "path": str(py.relative_to(REPO_DIR)),
        })

heuristics_df = pd.DataFrame(heuristic_rows)

print("\n=== LLM HEURISTICS AVAILABLE IN THE REPO CLONE ===")
if heuristics_df.empty:
    raise RuntimeError("No selected LLM heuristic .py files were found.")
else:
    display(heuristics_df)
    print("\nCounts by objective/variant:")
    display(heuristics_df.groupby(["objective", "variant", "center_constraint"]).size().reset_index(name="num_llm_heuristics"))

baseline_rows = []

baselines = cfg.get("baselines", []) or []
if isinstance(baselines, dict):
    # Backward-compatible display for old nested configs.
    for objective, methods in baselines.items():
        for method_id, method_cfg in (methods or {}).items():
            method_cfg = method_cfg or {}
            if bool(method_cfg.get("enabled", True)):
                baseline_rows.append({
                    "type": "external_baseline",
                    "objective": objective,
                    "method_id": method_id,
                    "enabled": True,
                    "repetitions_override": method_cfg.get("repetitions"),
                    "center_constraint": method_cfg.get("center_constraint"),
                    "max_n": method_cfg.get("max_n"),
                })
else:
    enabled_objectives = set(cfg.get("objectives", []))
    for b in baselines:
        if not b.get("enabled", True):
            continue
        for objective in sorted((set(b.get("objectives", [])) or enabled_objectives) & enabled_objectives):
            baseline_rows.append({
                "type": "external_baseline",
                "objective": objective,
                "method_id": b.get("id"),
                "enabled": True,
                "method_type": b.get("type", "python"),
                "repetitions_override": b.get("repetitions"),
                "center_constraint": b.get("center_constraint"),
                "max_n": b.get("max_n"),
            })

baseline_df = pd.DataFrame(baseline_rows)

print("\n=== EXTERNAL BASELINES ENABLED IN THE CONFIG ===")
if baseline_df.empty:
    print("No external baselines enabled.")
else:
    display(baseline_df)
    print("\nCounts by objective:")
    display(baseline_df.groupby("objective").size().reset_index(name="num_baselines"))

print("\n=== EXPECTED METHOD COUNTS BY OBJECTIVE BEFORE REPEATS ===")
llm_counts = heuristics_df.groupby("objective").size().reset_index(name="llm_selected")
base_counts = baseline_df.groupby("objective").size().reset_index(name="baselines") if not baseline_df.empty else pd.DataFrame(columns=["objective", "baselines"])
display(llm_counts.merge(base_counts, on="objective", how="outer").fillna(0))

=== RUNTIME CONFIG / PATHS ===
REPO_DIR: /content/llm-clustering-heuristics
Runtime config: /content/llm-clustering-heuristics/configs/final_eval_runtime.yaml
Runtime config exists: True

=== ACTIVE FINAL EVALUATION CONFIG ===
Objectives: ['sse', 'pmedian', 'radius']
Repetitions: 1
Timeout: 120
Artifact dir: /content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1
Cluster zip path: /content/drive/MyDrive/TM/cluster_tai.zip
Taillard C++ source path: external/taillard_cpp/clustering_sphere.cpp
Selected heuristics dir, as configured: experiments/selected_clustering_heuristics_final_by_objective
Reference tables: {'sse': '/content/drive/MyDrive/TM/kmeans.res', 'pmedian': '/content/drive/MyDrive/TM/kmeans.res', 'radius_free': None, 'radius_data_point': '/content/drive/MyDrive/TM/generator_radius_reference_last_p.zip', 'radius': None}

=== INSTANCE FILTERS ===
{'d_values': [2], 'p_values': [20], 'instance_ids': [0], 'min_n': None, 'max_n': None}

=== SELECTED LLM HEURISTICS SOURCE ===
Resolved local path: /content/llm-clustering-heuristics/experiments/selected_clustering_heuristics_final_by_objective
Exists: True

sse_free -> /content/llm-clustering-heuristics/experiments/selected_clustering_heuristics_final_by_objective/SSE_free_centers
objective: sse | center_constraint: free
exists: True | python files: 5

pmedian_data_point -> /content/llm-clustering-heuristics/experiments/selected_clustering_heuristics_final_by_objective/P_MEDIAN_data_point_centers
objective: pmedian | center_constraint: snap_to_points
exists: True | python files: 5

radius_free -> /content/llm-clustering-heuristics/experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_free_centers
objective: radius | center_constraint: free
exists: True | python files: 6

radius_data_point -> /content/llm-clustering-heuristics/experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_data_point_centers
objective: radius | center_constraint: snap_to_points
exists: True | python files: 7

=== LLM HEURISTICS AVAILABLE IN THE REPO CLONE ===

,type,objective,variant,center_constraint,method_folder,python_file,has_info_txt,has_source_row_json,path
0,llm_selected,sse,sse_free,free,01_candidate_037_best_quality,iter_037_485de21a19ccc6c83dc8.py,True,True,experiments/selected_clustering_heuristics_fin...
1,llm_selected,sse,sse_free,free,02_candidate_028_same_run_faster,iter_028_9d85b0c5e5d60ffc3c8c.py,True,True,experiments/selected_clustering_heuristics_fin...
2,llm_selected,sse,sse_free,free,03_candidate_028_edited_noise_injection,iter_028_e1054cdd0bb4ec67a203.py,True,True,experiments/selected_clustering_heuristics_fin...
3,llm_selected,sse,sse_free,free,04_candidate_013_gradient_momentum,iter_013_cdb12aa95b7ba4b22943.py,True,True,experiments/selected_clustering_heuristics_fin...
4,llm_selected,sse,sse_free,free,05_candidate_006_sampling_60p,iter_006_b691cc7629b192e3ddd3.py,True,True,experiments/selected_clustering_heuristics_fin...
5,llm_selected,pmedian,pmedian_data_point,snap_to_points,01_candidate_006_best_valid_nucleation,iter_006_9aaa459f60bce6d0581a.py,True,True,experiments/selected_clustering_heuristics_fin...
6,llm_selected,pmedian,pmedian_data_point,snap_to_points,02_candidate_007_best_raw_nucleation,iter_007_9d4cddf878e9f77f25d7.py,True,True,experiments/selected_clustering_heuristics_fin...
7,llm_selected,pmedian,pmedian_data_point,snap_to_points,03_ImprovedPMedianHeuristic4,iter_005_b37cc2250292527a3b99.py,True,True,experiments/selected_clustering_heuristics_fin...
8,llm_selected,pmedian,pmedian_data_point,snap_to_points,04_candidate_027_sampling_10p_quality,iter_027_704642fd2acc7b065e6b.py,True,True,experiments/selected_clustering_heuristics_fin...
9,llm_selected,pmedian,pmedian_data_point,snap_to_points,05_candidate_023_sampling_10p_fast,iter_023_3d8dd9872df5083be1d3.py,True,True,experiments/selected_clustering_heuristics_fin...
10,llm_selected,radius,radius_free,free,01_candidate_031_recursive_sphere_covering,iter_031_ece5273857c6ad69892e.py,True,True,experiments/selected_clustering_heuristics_fin...
11,llm_selected,radius,radius_free,free,02_candidate_035_recursive_sphere_covering_var...,iter_035_bf116e85544b051b8860.py,True,True,experiments/selected_clustering_heuristics_fin...
12,llm_selected,radius,radius_free,free,03_candidate_004_sampling_50p_full_valid,iter_004_48bcad7554bbc741b0f9.py,True,True,experiments/selected_clustering_heuristics_fin...
13,llm_selected,radius,radius_free,free,04_candidate_007_sampling_50p_best_gap,iter_007_c61d6da6ff3b1add3b89.py,True,True,experiments/selected_clustering_heuristics_fin...
14,llm_selected,radius,radius_free,free,05_candidate_008_sampling_20p_fast_broad,iter_008_9fd79ee04ed10179fc88.py,True,True,experiments/selected_clustering_heuristics_fin...
15,llm_selected,radius,radius_free,free,06_VolumeCovering_V5,iter_008_7f6a003aaa2f32ab3c38.py,True,True,experiments/selected_clustering_heuristics_fin...
16,llm_selected,radius,radius_data_point,snap_to_points,01_20260517_215015_candidate_042_best_final_qu...,iter_042_dcd5b9f129ed6e57faac.py,True,True,experiments/selected_clustering_heuristics_fin...
17,llm_selected,radius,radius_data_point,snap_to_points,02_20260517_215015_candidate_031_speed_quality...,iter_031_eaabf8b0e9dece65b4ea.py,True,True,experiments/selected_clustering_heuristics_fin...
18,llm_selected,radius,radius_data_point,snap_to_points,03_20260518_181812_candidate_004_hybrid_sampli...,iter_004_534024348fc00c7fd2a4.py,True,True,experiments/selected_clustering_heuristics_fin...
19,llm_selected,radius,radius_data_point,snap_to_points,04_20260518_181812_candidate_006_hybrid_sampli...,iter_006_56ff70324fde164dd947.py,True,True,experiments/selected_clustering_heuristics_fin...
20,llm_selected,radius,radius_data_point,snap_to_points,05_20260518_162854_candidate_020_fast_sample_b...,iter_020_123954358cb399940987.py,True,True,experiments/selected_clustering_heuristics_fin...
21,llm_selected,radius,radius_data_point,snap_to_points,06_20260517_191550_candidate_014_cluster_split...,iter_014_c5468f9eac829d7e22e3.py,True,True,experiments/selected_clustering_heuristics_fin...
22,llm_selected,radius,radius_data_point,snap_to_points,07_20260518_080147_candidate_008_dynamic_radiu...,iter_008_6ec3eed7b0944f9f2cbb.py,True,True,experiments/selected_clustering_heuristics_fin...

Counts by objective/variant:

  objective             variant center_constraint  num_llm_heuristics
0   pmedian  pmedian_data_point    snap_to_points                   5
1    radius   radius_data_point    snap_to_points                   7
2    radius         radius_free              free                   6
3       sse            sse_free              free                   5

=== EXTERNAL BASELINES ENABLED IN THE CONFIG ===

,type,objective,method_id,enabled,method_type,repetitions_override,center_constraint,max_n
0,external_baseline,radius,sklearn_kmeans_ninit20,True,python,30,None,None
1,external_baseline,sse,sklearn_kmeans_ninit20,True,python,30,None,None
2,external_baseline,radius,sklearn_minibatch_kmeans,True,python,30,None,None
3,external_baseline,sse,sklearn_minibatch_kmeans,True,python,30,None,None
4,external_baseline,radius,sklearn_bisecting_kmeans,True,python,30,None,None
5,external_baseline,sse,sklearn_bisecting_kmeans,True,python,30,None,None
6,external_baseline,pmedian,python_kmedoids_pam,True,python,10,snap_to_points,None
7,external_baseline,radius,python_kmedoids_pam,True,python,10,snap_to_points,None
8,external_baseline,pmedian,python_kmedoids_fastpam,True,python,10,snap_to_points,None
9,external_baseline,radius,python_kmedoids_fastpam,True,python,10,snap_to_points,None
10,external_baseline,pmedian,python_kmedoids_fasterpam,True,python,10,snap_to_points,None
11,external_baseline,radius,python_kmedoids_fasterpam,True,python,10,snap_to_points,None
12,external_baseline,pmedian,sklearn_extra_clara,True,python,30,snap_to_points,None
13,external_baseline,radius,sklearn_extra_clara,True,python,30,snap_to_points,None
14,external_baseline,radius,greedy_kcenter,True,python,30,snap_to_points,None
15,external_baseline,radius,taillard_cpp_kmedian,True,taillard_cpp,30,snap_to_points,None
16,external_baseline,radius,taillard_cpp_pam,True,taillard_cpp,30,snap_to_points,None
17,external_baseline,radius,taillard_cpp_hybrid_10p,True,taillard_cpp,30,snap_to_points,None

Counts by objective:

  objective  num_baselines
0   pmedian              4
1    radius             11
2       sse              3

=== EXPECTED METHOD COUNTS BY OBJECTIVE BEFORE REPEATS ===

  objective  llm_selected  baselines
0   pmedian             5          4
1    radius            13         11
2       sse             5          3

## 5. Check required files

In [32]:
from pathlib import Path

paths = {
    "cluster_zip_path": CLUSTER_ZIP_PATH,
    "taillard_cpp_source_path": TAILLARD_CPP_SOURCE_PATH,
    "sse_reference": SSE_REFERENCE_PATH,
    "pmedian_reference": PMEDIAN_REFERENCE_PATH,
    "radius_free_reference": RADIUS_FREE_REFERENCE_PATH,
    "radius_data_point_reference": RADIUS_DATA_POINT_REFERENCE_PATH,
}
for name, path in paths.items():
    if path is None:
        print(f"{name}: null")
    else:
        p = Path(path)
        print(f"{name}: {'OK' if p.exists() else 'MISSING'} -> {p}")

print("\nSelected heuristics folders:")
!find experiments/selected_clustering_heuristics_final_by_objective -maxdepth 3 -type f -name '*.py' | head -40

cluster_zip_path: OK -> /content/drive/MyDrive/TM/cluster_tai.zip
taillard_cpp_source_path: OK -> external/taillard_cpp/clustering_sphere.cpp
sse_reference: OK -> /content/drive/MyDrive/TM/kmeans.res
pmedian_reference: OK -> /content/drive/MyDrive/TM/kmeans.res
radius_free_reference: null
radius_data_point_reference: OK -> /content/drive/MyDrive/TM/generator_radius_reference_last_p.zip

Selected heuristics folders:
experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_free_centers/06_VolumeCovering_V5/iter_008_7f6a003aaa2f32ab3c38.py
experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_free_centers/05_candidate_008_sampling_20p_fast_broad/iter_008_9fd79ee04ed10179fc88.py
experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_free_centers/01_candidate_031_recursive_sphere_covering/iter_031_ece5273857c6ad69892e.py
experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_free_centers/02_candidate_035_recursive_sphere_covering_variant/iter_035_bf116e85544b051b8860.py
experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_free_centers/03_candidate_004_sampling_50p_full_valid/iter_004_48bcad7554bbc741b0f9.py
experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_free_centers/04_candidate_007_sampling_50p_best_gap/iter_007_c61d6da6ff3b1add3b89.py
experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_data_point_centers/06_20260517_191550_candidate_014_cluster_splitting_decomposition/iter_014_c5468f9eac829d7e22e3.py
experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_data_point_centers/05_20260518_162854_candidate_020_fast_sample_based_representative/iter_020_123954358cb399940987.py
experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_data_point_centers/03_20260518_181812_candidate_004_hybrid_sampling_full_repair_probe_robust/iter_004_534024348fc00c7fd2a4.py
experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_data_point_centers/07_20260518_080147_candidate_008_dynamic_radius_local_search/iter_008_6ec3eed7b0944f9f2cbb.py
experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_data_point_centers/02_20260517_215015_candidate_031_speed_quality_direct_repair/iter_031_eaabf8b0e9dece65b4ea.py
experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_data_point_centers/04_20260518_181812_candidate_006_hybrid_sampling_full_repair_search_strong/iter_006_56ff70324fde164dd947.py
experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_data_point_centers/01_20260517_215015_candidate_042_best_final_quality/iter_042_dcd5b9f129ed6e57faac.py
experiments/selected_clustering_heuristics_final_by_objective/P_MEDIAN_data_point_centers/05_candidate_023_sampling_10p_fast/iter_023_3d8dd9872df5083be1d3.py
experiments/selected_clustering_heuristics_final_by_objective/P_MEDIAN_data_point_centers/02_candidate_007_best_raw_nucleation/iter_007_9d4cddf878e9f77f25d7.py
experiments/selected_clustering_heuristics_final_by_objective/P_MEDIAN_data_point_centers/03_ImprovedPMedianHeuristic4/iter_005_b37cc2250292527a3b99.py
experiments/selected_clustering_heuristics_final_by_objective/P_MEDIAN_data_point_centers/04_candidate_027_sampling_10p_quality/iter_027_704642fd2acc7b065e6b.py
experiments/selected_clustering_heuristics_final_by_objective/P_MEDIAN_data_point_centers/01_candidate_006_best_valid_nucleation/iter_006_9aaa459f60bce6d0581a.py
experiments/selected_clustering_heuristics_final_by_objective/SSE_free_centers/01_candidate_037_best_quality/iter_037_485de21a19ccc6c83dc8.py
experiments/selected_clustering_heuristics_final_by_objective/SSE_free_centers/03_candidate_028_edited_noise_injection/iter_028_e1054cdd0bb4ec67a203.py
experiments/selected_clustering_heuristics_final_by_objective/SSE_free_centers/02_candidate_028_same_run_faster/iter_028_9d85b0c5e5d60ffc3c8c.py
experiments/selected_clustering_heuristics_final_by_objective/SSE_free_centers/04_candidate_013_gradient_momentum/iter_013_cdb12aa95b7ba4b22943.py
experiments/selected_clustering_heuristics_final_by_objective/SSE_free_centers/05_candidate_006_sampling_60p/iter_006_b691cc7629b192e3ddd3.py

## 6. Dry run / method manifest

In [33]:
import subprocess, sys

cmd = [sys.executable, "scripts/run_final_evaluation.py", "--config", str(runtime_cfg_path), "--dry-run"]
print(" ".join(cmd))
subprocess.run(cmd, check=True)

/usr/bin/python3 scripts/run_final_evaluation.py --config /content/llm-clustering-heuristics/configs/final_eval_runtime.yaml --dry-run

CompletedProcess(args=['/usr/bin/python3', 'scripts/run_final_evaluation.py', '--config', '/content/llm-clustering-heuristics/configs/final_eval_runtime.yaml', '--dry-run'], returncode=0)

## 7. Launch evaluation with live progress

In [34]:
import subprocess, sys, signal, os, time
from pathlib import Path

cmd = [sys.executable, "scripts/run_final_evaluation.py", "--config", str(runtime_cfg_path)]
if not RESUME:
    cmd.append("--no-resume")
if STOP_AFTER_JOBS is not None:
    cmd += ["--stop-after-jobs", str(STOP_AFTER_JOBS)]

print("Launching:", " ".join(cmd))
print("Stop safely with the notebook stop button / KeyboardInterrupt. Relaunch this same cell to resume.")

proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1)
try:
    assert proc.stdout is not None
    for line in proc.stdout:
        print(line, end="")
except KeyboardInterrupt:
    print("\nKeyboardInterrupt: forwarding SIGINT to evaluation process so it can checkpoint...")
    proc.send_signal(signal.SIGINT)
    try:
        proc.wait(timeout=30)
    except subprocess.TimeoutExpired:
        print("Process did not stop after SIGINT; terminating.")
        proc.terminate()
        proc.wait(timeout=10)
finally:
    rc = proc.poll()
    print("\nEvaluation process return code:", rc)

Launching: /usr/bin/python3 scripts/run_final_evaluation.py --config /content/llm-clustering-heuristics/configs/final_eval_runtime.yaml --no-resume
Stop safely with the notebook stop button / KeyboardInterrupt. Relaunch this same cell to resume.
Artifact dir: /content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1
Loaded 1 instances
Compiling Taillard C++ baseline: g++ -O2 external/taillard_cpp/clustering_sphere.cpp -o /content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1/taillard_cpp_build/clustering_sphere.exe
Taillard C++ binary: /content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1/taillard_cpp_build/clustering_sphere.exe
Methods: 41
Planned jobs: 443
[1/443] pmedian 01_candidate_006_best_valid_nucleation cluster_tai00400_020_2_0 rep=1
WARNING: CENTER_REPAIR: pmedian 01_candidate_006_best_valid_nucleation cluster_tai00400_020_2_0 rep=1: snapped_to_points (centers snapped to nearest data points for this objective)
[2/443] pmedian 02_candidate_007_best_raw_nucleation cluster_tai00400_020_2_0 rep=1, ETA≈0:01:31
WARNING: CENTER_REPAIR: pmedian 02_candidate_007_best_raw_nucleation cluster_tai00400_020_2_0 rep=1: snapped_to_points (centers snapped to nearest data points for this objective)
[3/443] pmedian 03_ImprovedPMedianHeuristic4 cluster_tai00400_020_2_0 rep=1, ETA≈0:01:55
[[0.3471794  0.4344432 ]
 [0.11436091 0.88596183]
 [0.80010255 0.14248381]
 [0.19700719 0.1377186 ]
 [0.78110763 0.75141797]]
WARNING: CENTER_REPAIR: pmedian 03_ImprovedPMedianHeuristic4 cluster_tai00400_020_2_0 rep=1: snapped_to_points (centers snapped to nearest data points for this objective)
[4/443] pmedian 04_candidate_027_sampling_10p_quality cluster_tai00400_020_2_0 rep=1, ETA≈0:01:29
WARNING: CENTER_REPAIR: pmedian 04_candidate_027_sampling_10p_quality cluster_tai00400_020_2_0 rep=1: snapped_to_points (centers snapped to nearest data points for this objective)
[5/443] pmedian 05_candidate_023_sampling_10p_fast cluster_tai00400_020_2_0 rep=1, ETA≈0:01:15
WARNING: CENTER_REPAIR: pmedian 05_candidate_023_sampling_10p_fast cluster_tai00400_020_2_0 rep=1: snapped_to_points (centers snapped to nearest data points for this objective)
[6/443] radius 01_20260517_215015_candidate_042_best_final_quality cluster_tai00400_020_2_0 rep=1, ETA≈0:01:06
WARNING: CENTER_REPAIR: radius 01_20260517_215015_candidate_042_best_final_quality cluster_tai00400_020_2_0 rep=1: snapped_to_points (centers snapped to nearest data points for this objective)
[7/443] radius 02_20260517_215015_candidate_031_speed_quality_direct_repair cluster_tai00400_020_2_0 rep=1, ETA≈0:21:45
WARNING: CENTER_REPAIR: radius 02_20260517_215015_candidate_031_speed_quality_direct_repair cluster_tai00400_020_2_0 rep=1: snapped_to_points (centers snapped to nearest data points for this objective)
[8/443] radius 03_20260518_181812_candidate_004_hybrid_sampling_full_repair_probe_robust cluster_tai00400_020_2_0 rep=1, ETA≈0:23:58
WARNING: CENTER_REPAIR: radius 03_20260518_181812_candidate_004_hybrid_sampling_full_repair_probe_robust cluster_tai00400_020_2_0 rep=1: snapped_to_points (centers snapped to nearest data points for this objective)
[9/443] radius 04_20260518_181812_candidate_006_hybrid_sampling_full_repair_search_strong cluster_tai00400_020_2_0 rep=1, ETA≈0:22:29
WARNING: CENTER_REPAIR: radius 04_20260518_181812_candidate_006_hybrid_sampling_full_repair_search_strong cluster_tai00400_020_2_0 rep=1: snapped_to_points (centers snapped to nearest data points for this objective)
[10/443] radius 05_20260518_162854_candidate_020_fast_sample_based_representative cluster_tai00400_020_2_0 rep=1, ETA≈0:21:13
WARNING: CENTER_REPAIR: radius 05_20260518_162854_candidate_020_fast_sample_based_representative cluster_tai00400_020_2_0 rep=1: snapped_to_points (centers snapped to nearest data points for this objective)
[11/443] radius 06_20260517_191550_candidate_014_cluster_splitting_decomposition cluster_tai00400_020_2_0 rep=1, ETA≈0:19:07
/content/llm-clustering-heuristics/experiments/selected_clustering_heuristics_final_by_objective/RADIUS_VOLUME_data_point_centers/06_20260517_191550_candidate_014_cluster_splitting_decomposition/iter_014_c5468f9eac829d7e22e3.py:83: RuntimeWarning: invalid value encountered in multiply
  distances_to_self = np.eye(points_in_cluster.shape[0]) * np.inf
WARNING: CENTER_REPAIR: radius 06_20260517_191550_candidate_014_cluster_splitting_decomposition cluster_tai00400_020_2_0 rep=1: snapped_to_points (centers snapped to nearest data points for this objective)
[12/443] radius 07_20260518_080147_candidate_008_dynamic_radius_local_search cluster_tai00400_020_2_0 rep=1, ETA≈0:18:12
WARNING: CENTER_REPAIR: radius 07_20260518_080147_candidate_008_dynamic_radius_local_search cluster_tai00400_020_2_0 rep=1: snapped_to_points (centers snapped to nearest data points for this objective)
[13/443] radius 01_candidate_031_recursive_sphere_covering cluster_tai00400_020_2_0 rep=1, ETA≈0:17:00
[14/443] radius 02_candidate_035_recursive_sphere_covering_variant cluster_tai00400_020_2_0 rep=1, ETA≈0:15:44
[15/443] radius 03_candidate_004_sampling_50p_full_valid cluster_tai00400_020_2_0 rep=1, ETA≈0:14:39
[16/443] radius 04_candidate_007_sampling_50p_best_gap cluster_tai00400_020_2_0 rep=1, ETA≈0:13:41
[17/443] radius 05_candidate_008_sampling_20p_fast_broad cluster_tai00400_020_2_0 rep=1, ETA≈0:12:51
[18/443] radius 06_VolumeCovering_V5 cluster_tai00400_020_2_0 rep=1, ETA≈0:12:05
[19/443] sse 01_candidate_037_best_quality cluster_tai00400_020_2_0 rep=1, ETA≈0:11:28
[20/443] sse 02_candidate_028_same_run_faster cluster_tai00400_020_2_0 rep=1, ETA≈0:11:00
[21/443] sse 03_candidate_028_edited_noise_injection cluster_tai00400_020_2_0 rep=1, ETA≈0:10:32
[22/443] sse 04_candidate_013_gradient_momentum cluster_tai00400_020_2_0 rep=1, ETA≈0:10:08
[23/443] sse 05_candidate_006_sampling_60p cluster_tai00400_020_2_0 rep=1, ETA≈0:09:43
[24/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=1, ETA≈0:09:17
[25/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=2, ETA≈0:09:10
[26/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=3, ETA≈0:09:04
[27/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=4, ETA≈0:08:57
[28/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=5, ETA≈0:08:52
[29/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=6, ETA≈0:08:46
[30/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=7, ETA≈0:08:41
[31/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=8, ETA≈0:08:37
[32/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=9, ETA≈0:08:39
[33/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=10, ETA≈0:08:40
[34/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=11, ETA≈0:08:41
[35/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=12, ETA≈0:08:36
[36/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=13, ETA≈0:08:31
[37/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=14, ETA≈0:08:27
[38/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=15, ETA≈0:08:23
[39/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=16, ETA≈0:08:19
[40/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=17, ETA≈0:08:16
[41/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=18, ETA≈0:08:12
[42/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=19, ETA≈0:08:08
[43/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=20, ETA≈0:08:05
[44/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=21, ETA≈0:08:02
[45/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=22, ETA≈0:08:03
[46/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=23, ETA≈0:08:04
[47/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=24, ETA≈0:08:04
[48/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=25, ETA≈0:08:02
[49/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=26, ETA≈0:07:59
[50/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=27, ETA≈0:07:56
[51/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=28, ETA≈0:07:53
[52/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=29, ETA≈0:07:50
[53/443] radius sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=30, ETA≈0:07:47
[54/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=1, ETA≈0:07:44
[55/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=2, ETA≈0:07:42
[56/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=3, ETA≈0:07:39
[57/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=4, ETA≈0:07:37
[58/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=5, ETA≈0:07:37
[59/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=6, ETA≈0:07:38
[60/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=7, ETA≈0:07:39
[61/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=8, ETA≈0:07:37
[62/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=9, ETA≈0:07:35
[63/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=10, ETA≈0:07:33
[64/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=11, ETA≈0:07:31
[65/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=12, ETA≈0:07:28
[66/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=13, ETA≈0:07:26
[67/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=14, ETA≈0:07:24
[68/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=15, ETA≈0:07:22
[69/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=16, ETA≈0:07:20
[70/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=17, ETA≈0:07:19
[71/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=18, ETA≈0:07:19
[72/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=19, ETA≈0:07:19
[73/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=20, ETA≈0:07:20
[74/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=21, ETA≈0:07:18
[75/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=22, ETA≈0:07:16
[76/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=23, ETA≈0:07:15
[77/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=24, ETA≈0:07:15
[78/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=25, ETA≈0:07:13
[79/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=26, ETA≈0:07:11
[80/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=27, ETA≈0:07:09
[81/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=28, ETA≈0:07:07
[82/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=29, ETA≈0:07:05
[83/443] sse sklearn_kmeans_ninit20 cluster_tai00400_020_2_0 rep=30, ETA≈0:07:05
[84/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=1, ETA≈0:07:06
[85/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=2, ETA≈0:07:05
[86/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=3, ETA≈0:07:03
[87/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=4, ETA≈0:07:01
[88/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=5, ETA≈0:06:59
[89/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=6, ETA≈0:06:57
[90/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=7, ETA≈0:06:55
[91/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=8, ETA≈0:06:53
[92/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=9, ETA≈0:06:51
[93/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=10, ETA≈0:06:49
[94/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=11, ETA≈0:06:47
[95/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=12, ETA≈0:06:45
[96/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=13, ETA≈0:06:44
[97/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=14, ETA≈0:06:43
[98/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=15, ETA≈0:06:43
[99/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=16, ETA≈0:06:42
[100/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=17, ETA≈0:06:40
[101/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=18, ETA≈0:06:38
[102/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=19, ETA≈0:06:36
[103/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=20, ETA≈0:06:34
[104/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=21, ETA≈0:06:33
[105/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=22, ETA≈0:06:31
[106/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=23, ETA≈0:06:29
[107/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=24, ETA≈0:06:27
[108/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=25, ETA≈0:06:25
[109/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=26, ETA≈0:06:24
[110/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=27, ETA≈0:06:23
[111/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=28, ETA≈0:06:22
[112/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=29, ETA≈0:06:22
[113/443] radius sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=30, ETA≈0:06:21
[114/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=1, ETA≈0:06:19
[115/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=2, ETA≈0:06:17
[116/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=3, ETA≈0:06:16
[117/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=4, ETA≈0:06:14
[118/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=5, ETA≈0:06:12
[119/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=6, ETA≈0:06:10
[120/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=7, ETA≈0:06:09
[121/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=8, ETA≈0:06:07
[122/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=9, ETA≈0:06:05
[123/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=10, ETA≈0:06:04
[124/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=11, ETA≈0:06:03
[125/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=12, ETA≈0:06:02
[126/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=13, ETA≈0:06:02
[127/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=14, ETA≈0:06:01
[128/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=15, ETA≈0:05:59
[129/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=16, ETA≈0:05:58
[130/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=17, ETA≈0:05:56
[131/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=18, ETA≈0:05:54
[132/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=19, ETA≈0:05:53
[133/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=20, ETA≈0:05:51
[134/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=21, ETA≈0:05:50
[135/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=22, ETA≈0:05:48
[136/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=23, ETA≈0:05:47
[137/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=24, ETA≈0:05:45
[138/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=25, ETA≈0:05:44
[139/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=26, ETA≈0:05:43
[140/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=27, ETA≈0:05:43
[141/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=28, ETA≈0:05:42
[142/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=29, ETA≈0:05:40
[143/443] sse sklearn_minibatch_kmeans cluster_tai00400_020_2_0 rep=30, ETA≈0:05:39
[144/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=1, ETA≈0:05:37
[145/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=2, ETA≈0:05:36
[146/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=3, ETA≈0:05:34
[147/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=4, ETA≈0:05:33
[148/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=5, ETA≈0:05:31
[149/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=6, ETA≈0:05:30
[150/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=7, ETA≈0:05:29
[151/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=8, ETA≈0:05:27
[152/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=9, ETA≈0:05:27
[153/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=10, ETA≈0:05:26
[154/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=11, ETA≈0:05:25
[155/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=12, ETA≈0:05:24
[156/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=13, ETA≈0:05:23
[157/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=14, ETA≈0:05:21
[158/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=15, ETA≈0:05:20
[159/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=16, ETA≈0:05:18
[160/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=17, ETA≈0:05:17
[161/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=18, ETA≈0:05:16
[162/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=19, ETA≈0:05:16
[163/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=20, ETA≈0:05:17
[164/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=21, ETA≈0:05:16
[165/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=22, ETA≈0:05:16
[166/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=23, ETA≈0:05:15
[167/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=24, ETA≈0:05:13
[168/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=25, ETA≈0:05:12
[169/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=26, ETA≈0:05:10
[170/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=27, ETA≈0:05:09
[171/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=28, ETA≈0:05:08
[172/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=29, ETA≈0:05:06
[173/443] radius sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=30, ETA≈0:05:05
[174/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=1, ETA≈0:05:03
[175/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=2, ETA≈0:05:02
[176/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=3, ETA≈0:05:01
[177/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=4, ETA≈0:05:00
[178/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=5, ETA≈0:05:00
[179/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=6, ETA≈0:04:59
[180/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=7, ETA≈0:04:58
[181/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=8, ETA≈0:04:56
[182/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=9, ETA≈0:04:55
[183/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=10, ETA≈0:04:54
[184/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=11, ETA≈0:04:52
[185/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=12, ETA≈0:04:51
[186/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=13, ETA≈0:04:50
[187/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=14, ETA≈0:04:48
[188/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=15, ETA≈0:04:47
[189/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=16, ETA≈0:04:46
[190/443] sse sklearn_bisecting_kmeans cluster_tai00400_020_2_0 rep=17, ETA≈0:04:45

## Post-launch visibility

Run these cells after launching the evaluation to see which methods were actually loaded and what progress has been checkpointed.

In [35]:
from pathlib import Path
import pandas as pd
from IPython.display import display

artifact_dir = Path(ARTIFACT_DIR + ("_smoke" if SMOKE_TEST else ""))
manifest_path = artifact_dir / "method_manifest.csv"

print("=== ACTUALLY LOADED METHODS AFTER RUNNER STARTED ===")
print("Artifact dir:", artifact_dir)
print("Method manifest:", manifest_path)
print("Exists:", manifest_path.exists())

if manifest_path.exists() and manifest_path.stat().st_size > 0:
    manifest = pd.read_csv(manifest_path)
    print("Loaded methods:", len(manifest))
    display(manifest)

    print("\nCounts:")
    display(
        manifest.groupby(["objective", "method_group"])
        .size()
        .reset_index(name="num_methods")
    )
else:
    print("No method_manifest.csv yet. Launch the evaluation cell first.")

=== ACTUALLY LOADED METHODS AFTER RUNNER STARTED ===
Artifact dir: /content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1
Method manifest: /content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1/method_manifest.csv
Exists: True
Loaded methods: 41

,method_id,method_group,method_type,objective,center_constraint,method_variant,reference_key,path,relative_path,info_text,params,max_n,repetitions,cpp_option
0,01_candidate_006_best_valid_nucleation,llm_selected,python,pmedian,snap_to_points,pmedian_data_point,pmedian,experiments/selected_clustering_heuristics_fin...,P_MEDIAN_data_point_centers/01_candidate_006_b...,p-median candidate 6\n\nObjective folder: P_ME...,NaN,NaN,NaN,NaN
1,02_candidate_007_best_raw_nucleation,llm_selected,python,pmedian,snap_to_points,pmedian_data_point,pmedian,experiments/selected_clustering_heuristics_fin...,P_MEDIAN_data_point_centers/02_candidate_007_b...,p-median candidate 7\n\nObjective folder: P_ME...,NaN,NaN,NaN,NaN
2,03_ImprovedPMedianHeuristic4,llm_selected,python,pmedian,snap_to_points,pmedian_data_point,pmedian,experiments/selected_clustering_heuristics_fin...,P_MEDIAN_data_point_centers/03_ImprovedPMedian...,ImprovedPMedianHeuristic4\n\nObjective folder:...,NaN,NaN,NaN,NaN
3,04_candidate_027_sampling_10p_quality,llm_selected,python,pmedian,snap_to_points,pmedian_data_point,pmedian,experiments/selected_clustering_heuristics_fin...,P_MEDIAN_data_point_centers/04_candidate_027_s...,p-median sampling candidate 27\n\nObjective fo...,NaN,NaN,NaN,NaN
4,05_candidate_023_sampling_10p_fast,llm_selected,python,pmedian,snap_to_points,pmedian_data_point,pmedian,experiments/selected_clustering_heuristics_fin...,P_MEDIAN_data_point_centers/05_candidate_023_s...,p-median sampling candidate 23\n\nObjective fo...,NaN,NaN,NaN,NaN
5,01_20260517_215015_candidate_042_best_final_qu...,llm_selected,python,radius,snap_to_points,radius_data_point,radius_data_point,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_data_point_centers/01_20260517_2...,20260517_215015 candidate 42\n\nObjective fold...,NaN,NaN,NaN,NaN
6,02_20260517_215015_candidate_031_speed_quality...,llm_selected,python,radius,snap_to_points,radius_data_point,radius_data_point,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_data_point_centers/02_20260517_2...,20260517_215015 candidate 31\n\nObjective fold...,NaN,NaN,NaN,NaN
7,03_20260518_181812_candidate_004_hybrid_sampli...,llm_selected,python,radius,snap_to_points,radius_data_point,radius_data_point,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_data_point_centers/03_20260518_1...,20260518_181812 candidate 4\n\nObjective folde...,NaN,NaN,NaN,NaN
8,04_20260518_181812_candidate_006_hybrid_sampli...,llm_selected,python,radius,snap_to_points,radius_data_point,radius_data_point,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_data_point_centers/04_20260518_1...,20260518_181812 candidate 6\n\nObjective folde...,NaN,NaN,NaN,NaN
9,05_20260518_162854_candidate_020_fast_sample_b...,llm_selected,python,radius,snap_to_points,radius_data_point,radius_data_point,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_data_point_centers/05_20260518_1...,20260518_162854 candidate 20\n\nObjective fold...,NaN,NaN,NaN,NaN
10,06_20260517_191550_candidate_014_cluster_split...,llm_selected,python,radius,snap_to_points,radius_data_point,radius_data_point,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_data_point_centers/06_20260517_1...,20260517_191550 candidate 14\n\nObjective fold...,NaN,NaN,NaN,NaN
11,07_20260518_080147_candidate_008_dynamic_radiu...,llm_selected,python,radius,snap_to_points,radius_data_point,radius_data_point,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_data_point_centers/07_20260518_0...,20260518_080147 candidate 8\n\nObjective folde...,NaN,NaN,NaN,NaN
12,01_candidate_031_recursive_sphere_covering,llm_selected,python,radius,free,radius_free,radius_free,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_free_centers/01_candidate_031_re...,radius recursive sphere-covering candidate 31\...,NaN,NaN,NaN,NaN
13,02_candidate_035_recursive_sphere_covering_var...,llm_selected,python,radius,free,radius_free,radius_free,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_free_centers/02_candidate_035_re...,radius recursive sphere-covering candidate 35\...,NaN,NaN,NaN,NaN
14,03_candidate_004_sampling_50p_full_valid,llm_selected,python,radius,free,radius_free,radius_free,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_free_centers/03_candidate_004_sa...,radius sample_50p candidate 4\n\nObjective fol...,NaN,NaN,NaN,NaN
15,04_candidate_007_sampling_50p_best_gap,llm_selected,python,radius,free,radius_free,radius_free,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_free_centers/04_candidate_007_sa...,radius sample_50p candidate 7\n\nObjective fol...,NaN,NaN,NaN,NaN
16,05_candidate_008_sampling_20p_fast_broad,llm_selected,python,radius,free,radius_free,radius_free,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_free_centers/05_candidate_008_sa...,radius sampling 20p candidate 8\n\nObjective f...,NaN,NaN,NaN,NaN
17,06_VolumeCovering_V5,llm_selected,python,radius,free,radius_free,radius_free,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_free_centers/06_VolumeCovering_V...,VolumeCovering V5\n\nObjective folder: RADIUS_...,NaN,NaN,NaN,NaN
18,01_candidate_037_best_quality,llm_selected,python,sse,free,sse_free,sse,experiments/selected_clustering_heuristics_fin...,SSE_free_centers/01_candidate_037_best_quality...,SSE candidate 37\n\nObjective folder: SSE_free...,NaN,NaN,NaN,NaN
19,02_candidate_028_same_run_faster,llm_selected,python,sse,free,sse_free,sse,experiments/selected_clustering_heuristics_fin...,SSE_free_centers/02_candidate_028_same_run_fas...,"SSE candidate 28, same run\n\nObjective folder...",NaN,NaN,NaN,NaN
20,03_candidate_028_edited_noise_injection,llm_selected,python,sse,free,sse_free,sse,experiments/selected_clustering_heuristics_fin...,SSE_free_centers/03_candidate_028_edited_noise...,SSE edited candidate 28\n\nObjective folder: S...,NaN,NaN,NaN,NaN
21,04_candidate_013_gradient_momentum,llm_selected,python,sse,free,sse_free,sse,experiments/selected_clustering_heuristics_fin...,SSE_free_centers/04_candidate_013_gradient_mom...,SSE gradient/momentum candidate 13\n\nObjectiv...,NaN,NaN,NaN,NaN
22,05_candidate_006_sampling_60p,llm_selected,python,sse,free,sse_free,sse,experiments/selected_clustering_heuristics_fin...,SSE_free_centers/05_candidate_006_sampling_60p...,SSE sampling 60p candidate 6\n\nObjective fold...,NaN,NaN,NaN,NaN
23,sklearn_kmeans_ninit20,external_baseline,python,radius,NaN,radius_free,radius_free,NaN,NaN,NaN,{'n_init': 20},NaN,30.0,NaN
24,sklearn_kmeans_ninit20,external_baseline,python,sse,NaN,sse,sse,NaN,NaN,NaN,{'n_init': 20},NaN,30.0,NaN
25,sklearn_minibatch_kmeans,external_baseline,python,radius,NaN,radius_free,radius_free,NaN,NaN,NaN,{'n_init': 10},NaN,30.0,NaN
26,sklearn_minibatch_kmeans,external_baseline,python,sse,NaN,sse,sse,NaN,NaN,NaN,{'n_init': 10},NaN,30.0,NaN
27,sklearn_bisecting_kmeans,external_baseline,python,radius,NaN,radius_free,radius_free,NaN,NaN,NaN,{'n_init': 5},NaN,30.0,NaN
28,sklearn_bisecting_kmeans,external_baseline,python,sse,NaN,sse,sse,NaN,NaN,NaN,{'n_init': 5},NaN,30.0,NaN
29,python_kmedoids_pam,external_baseline,python,pmedian,snap_to_points,pmedian,pmedian,NaN,NaN,NaN,{},NaN,10.0,NaN
30,python_kmedoids_pam,external_baseline,python,radius,snap_to_points,radius_data_point,radius_data_point,NaN,NaN,NaN,{},NaN,10.0,NaN
31,python_kmedoids_fastpam,external_baseline,python,pmedian,snap_to_points,pmedian,pmedian,NaN,NaN,NaN,{},NaN,10.0,NaN
32,python_kmedoids_fastpam,external_baseline,python,radius,snap_to_points,radius_data_point,radius_data_point,NaN,NaN,NaN,{},NaN,10.0,NaN
33,python_kmedoids_fasterpam,external_baseline,python,pmedian,snap_to_points,pmedian,pmedian,NaN,NaN,NaN,{},NaN,10.0,NaN
34,python_kmedoids_fasterpam,external_baseline,python,radius,snap_to_points,radius_data_point,radius_data_point,NaN,NaN,NaN,{},NaN,10.0,NaN
35,sklearn_extra_clara,external_baseline,python,pmedian,snap_to_points,pmedian,pmedian,NaN,NaN,NaN,{},NaN,30.0,NaN
36,sklearn_extra_clara,external_baseline,python,radius,snap_to_points,radius_data_point,radius_data_point,NaN,NaN,NaN,{},NaN,30.0,NaN
37,greedy_kcenter,external_baseline,python,radius,snap_to_points,radius_data_point,radius_data_point,NaN,NaN,NaN,{},NaN,30.0,NaN
38,taillard_cpp_kmedian,taillard_cpp,taillard_cpp,radius,snap_to_points,radius_data_point,radius_data_point,NaN,NaN,NaN,{},NaN,30.0,0.0
39,taillard_cpp_pam,taillard_cpp,taillard_cpp,radius,snap_to_points,radius_data_point,radius_data_point,NaN,NaN,NaN,{},NaN,30.0,1.0
40,taillard_cpp_hybrid_10p,taillard_cpp,taillard_cpp,radius,snap_to_points,radius_data_point,radius_data_point,NaN,NaN,NaN,{},NaN,30.0,2.0

Counts:

  objective       method_group  num_methods
0   pmedian  external_baseline            4
1   pmedian       llm_selected            5
2    radius  external_baseline            8
3    radius       llm_selected           13
4    radius       taillard_cpp            3
5       sse  external_baseline            3
6       sse       llm_selected            5

In [36]:
from pathlib import Path
import pandas as pd
import json
from IPython.display import display

artifact_dir = Path(ARTIFACT_DIR + ("_smoke" if SMOKE_TEST else ""))

progress_path = artifact_dir / "progress_state.json"
checkpoint_path = artifact_dir / "raw_runs_checkpoint.csv"
log_path = artifact_dir / "logs" / "progress.log"

print("=== LIVE / CHECKPOINT PROGRESS ===")
print("Artifact dir:", artifact_dir)

print("\n--- progress_state.json ---")
if progress_path.exists():
    try:
        print(json.dumps(json.loads(progress_path.read_text()), indent=2)[:5000])
    except Exception as e:
        print("Could not parse progress_state.json:", repr(e))
        print(progress_path.read_text(errors="replace")[:2000])
else:
    print("No progress_state.json yet.")

print("\n--- last checkpointed runs ---")
if checkpoint_path.exists() and checkpoint_path.stat().st_size > 0:
    df = pd.read_csv(checkpoint_path)
    print("Rows completed:", len(df))
    cols = [
        "objective", "method_group", "method_id", "instance", "rep",
        "success", "timeout", "runtime_s", "objective_value", "gap_pct", "error"
    ]
    cols = [c for c in cols if c in df.columns]
    display(df.tail(30)[cols])
else:
    print("No raw_runs_checkpoint.csv yet.")

print("\n--- last progress log lines ---")
if log_path.exists():
    lines = log_path.read_text(errors="replace").splitlines()
    print("\n".join(lines[-60:]))
else:
    print("No progress.log yet.")

=== LIVE / CHECKPOINT PROGRESS ===
Artifact dir: /content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1

--- progress_state.json ---
{
  "status": "finished_or_stopped",
  "artifact_dir": "/content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1",
  "planned_jobs": 443,
  "completed_jobs": 443,
  "new_jobs_this_process": 443,
  "raw_runs_checkpoint": "/content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1/raw_runs_checkpoint.csv",
  "updated_at": "2026-05-21T14:48:49"
}

--- last checkpointed runs ---
Rows completed: 443

,objective,method_group,method_id,instance,rep,success,timeout,runtime_s,objective_value,gap_pct,error
413,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,0,True,False,0.145022,9914.00192,46.138,NaN
414,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,1,True,False,0.081634,7410.97728,9.242,NaN
415,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,2,True,False,0.104634,7764.96640,14.460,NaN
416,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,3,True,False,0.086962,7506.97088,10.657,NaN
417,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,4,True,False,0.093321,7579.01696,11.719,NaN
418,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,5,True,False,0.087121,9282.00448,36.822,NaN
419,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,6,True,False,0.083546,10455.97568,54.127,NaN
420,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,7,True,False,0.108111,11279.01056,66.259,NaN
421,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,8,True,False,0.085755,8357.00608,23.187,NaN
422,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,9,True,False,0.084586,7556.01920,11.380,NaN
423,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,10,True,False,0.084712,8019.97696,18.219,NaN
424,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,11,True,False,0.095030,7526.03392,10.938,NaN
425,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,12,True,False,0.086157,9130.99264,34.596,NaN
426,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,13,True,False,0.096675,8330.00576,22.789,NaN
427,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,14,True,False,0.083508,8034.96960,18.440,NaN
428,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,15,True,False,0.088181,7344.96896,8.269,NaN
429,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,16,True,False,0.086760,9102.02496,34.169,NaN
430,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,17,True,False,0.087136,7432.00768,9.552,NaN
431,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,18,True,False,0.082575,8058.98496,18.794,NaN
432,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,19,True,False,0.127649,8096.97536,19.354,NaN
433,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,20,True,False,0.138156,8334.00832,22.848,NaN
434,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,21,True,False,0.130794,7834.97728,15.492,NaN
435,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,22,True,False,0.133125,8519.00800,25.575,NaN
436,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,23,True,False,0.145634,7969.02912,17.468,NaN
437,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,24,True,False,0.090368,7762.99904,14.431,NaN
438,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,25,True,False,0.087996,8400.96640,23.835,NaN
439,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,26,True,False,0.085776,9055.01184,33.476,NaN
440,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,27,True,False,0.088101,10937.97888,61.232,NaN
441,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,28,True,False,0.086220,8539.97056,25.884,NaN
442,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,29,True,False,0.085231,9101.00736,34.154,NaN

--- last progress log lines ---
2026-05-21T14:47:59 [384/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=1, ETA≈0:00:55
2026-05-21T14:48:01 [385/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=2, ETA≈0:00:54
2026-05-21T14:48:02 [386/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=3, ETA≈0:00:54
2026-05-21T14:48:03 [387/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=4, ETA≈0:00:53
2026-05-21T14:48:04 [388/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=5, ETA≈0:00:52
2026-05-21T14:48:05 [389/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=6, ETA≈0:00:51
2026-05-21T14:48:06 [390/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=7, ETA≈0:00:50
2026-05-21T14:48:07 [391/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=8, ETA≈0:00:49
2026-05-21T14:48:08 [392/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=9, ETA≈0:00:48
2026-05-21T14:48:09 [393/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=10, ETA≈0:00:47
2026-05-21T14:48:10 [394/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=11, ETA≈0:00:46
2026-05-21T14:48:11 [395/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=12, ETA≈0:00:45
2026-05-21T14:48:11 [396/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=13, ETA≈0:00:44
2026-05-21T14:48:12 [397/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=14, ETA≈0:00:43
2026-05-21T14:48:14 [398/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=15, ETA≈0:00:42
2026-05-21T14:48:15 [399/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=16, ETA≈0:00:42
2026-05-21T14:48:16 [400/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=17, ETA≈0:00:41
2026-05-21T14:48:17 [401/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=18, ETA≈0:00:40
2026-05-21T14:48:18 [402/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=19, ETA≈0:00:39
2026-05-21T14:48:19 [403/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=20, ETA≈0:00:38
2026-05-21T14:48:20 [404/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=21, ETA≈0:00:37
2026-05-21T14:48:21 [405/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=22, ETA≈0:00:36
2026-05-21T14:48:22 [406/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=23, ETA≈0:00:35
2026-05-21T14:48:23 [407/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=24, ETA≈0:00:34
2026-05-21T14:48:24 [408/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=25, ETA≈0:00:33
2026-05-21T14:48:24 [409/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=26, ETA≈0:00:32
2026-05-21T14:48:25 [410/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=27, ETA≈0:00:31
2026-05-21T14:48:26 [411/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=28, ETA≈0:00:30
2026-05-21T14:48:27 [412/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=29, ETA≈0:00:29
2026-05-21T14:48:29 [413/443] radius taillard_cpp_pam cluster_tai00400_020_2_0 rep=30, ETA≈0:00:28
2026-05-21T14:48:30 [414/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=1, ETA≈0:00:28
2026-05-21T14:48:31 [415/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=2, ETA≈0:00:27
2026-05-21T14:48:32 [416/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=3, ETA≈0:00:26
2026-05-21T14:48:32 [417/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=4, ETA≈0:00:25
2026-05-21T14:48:33 [418/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=5, ETA≈0:00:24
2026-05-21T14:48:33 [419/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=6, ETA≈0:00:23
2026-05-21T14:48:34 [420/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=7, ETA≈0:00:22
2026-05-21T14:48:35 [421/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=8, ETA≈0:00:21
2026-05-21T14:48:35 [422/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=9, ETA≈0:00:20
2026-05-21T14:48:36 [423/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=10, ETA≈0:00:19
2026-05-21T14:48:36 [424/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=11, ETA≈0:00:18
2026-05-21T14:48:37 [425/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=12, ETA≈0:00:17
2026-05-21T14:48:37 [426/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=13, ETA≈0:00:16
2026-05-21T14:48:38 [427/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=14, ETA≈0:00:15
2026-05-21T14:48:39 [428/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=15, ETA≈0:00:14
2026-05-21T14:48:39 [429/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=16, ETA≈0:00:13
2026-05-21T14:48:40 [430/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=17, ETA≈0:00:12
2026-05-21T14:48:40 [431/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=18, ETA≈0:00:11
2026-05-21T14:48:41 [432/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=19, ETA≈0:00:11
2026-05-21T14:48:41 [433/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=20, ETA≈0:00:10
2026-05-21T14:48:42 [434/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=21, ETA≈0:00:09
2026-05-21T14:48:43 [435/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=22, ETA≈0:00:08
2026-05-21T14:48:44 [436/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=23, ETA≈0:00:07
2026-05-21T14:48:45 [437/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=24, ETA≈0:00:06
2026-05-21T14:48:46 [438/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=25, ETA≈0:00:05
2026-05-21T14:48:46 [439/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=26, ETA≈0:00:04
2026-05-21T14:48:47 [440/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=27, ETA≈0:00:03
2026-05-21T14:48:47 [441/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=28, ETA≈0:00:02
2026-05-21T14:48:48 [442/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=29, ETA≈0:00:01
2026-05-21T14:48:48 [443/443] radius taillard_cpp_hybrid_10p cluster_tai00400_020_2_0 rep=30, ETA≈0:00:00

## Safe result display

This version does not crash when `complexity_fit.csv` is empty during small smoke tests.

In [37]:
from pathlib import Path
import pandas as pd
from pandas.errors import EmptyDataError
from IPython.display import display, Image

artifact_dir = Path(ARTIFACT_DIR + ("_smoke" if SMOKE_TEST else ""))

print("Artifact dir:", artifact_dir)

for name in [
    "method_summary.csv",
    "instance_summary.csv",
    "complexity_fit.csv",
    "complexity_fit_points.csv",
    "center_repair_warning_counts.json",
]:
    p = artifact_dir / name
    print("\n", name, "->", "OK" if p.exists() else "missing")

    if not p.exists():
        continue

    if p.suffix == ".csv":
        if p.stat().st_size == 0:
            print("File exists but is empty. This is normal when there are not enough data points, e.g. smoke complexity with only one n.")
            continue

        try:
            df = pd.read_csv(p)
            if df.empty:
                print("CSV has columns but no rows.")
            else:
                display(df.head(30))
        except EmptyDataError:
            print("CSV exists but has no parseable columns. Usually means no data was available for this summary.")
    else:
        print(p.read_text(errors="replace")[:3000])

plot_dir = artifact_dir / "complexity_plots"
if plot_dir.exists():
    pngs = sorted(plot_dir.glob("*.png"))
    if not pngs:
        print("\ncomplexity_plots exists but contains no PNG yet.")
    for png in pngs:
        print("\n", png.name)
        display(Image(filename=str(png)))
else:
    print("\nNo complexity_plots directory yet.")

zip_path = str(artifact_dir) + ".zip"
print("\nArtifact zip:", zip_path, "exists=", Path(zip_path).exists())

Artifact dir: /content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1

 method_summary.csv -> OK

,objective,method_group,method_id,instances,median_gap_over_instances,mean_gap_over_instances,p10_gap_over_instances,p90_gap_over_instances,median_runtime_over_instances,success_rate_mean,timeout_rate_mean
0,pmedian,external_baseline,python_kmedoids_fasterpam,1,NaN,NaN,NaN,NaN,0.840772,1.0,0.0
1,pmedian,external_baseline,python_kmedoids_pam,1,NaN,NaN,NaN,NaN,0.935365,1.0,0.0
2,pmedian,llm_selected,01_candidate_006_best_valid_nucleation,1,NaN,NaN,NaN,NaN,0.145281,1.0,0.0
3,pmedian,llm_selected,02_candidate_007_best_raw_nucleation,1,NaN,NaN,NaN,NaN,0.259777,1.0,0.0
4,pmedian,llm_selected,03_ImprovedPMedianHeuristic4,1,NaN,NaN,NaN,NaN,0.023769,1.0,0.0
5,pmedian,llm_selected,04_candidate_027_sampling_10p_quality,1,NaN,NaN,NaN,NaN,0.028451,1.0,0.0
6,pmedian,llm_selected,05_candidate_023_sampling_10p_fast,1,NaN,NaN,NaN,NaN,0.013696,1.0,0.0
7,radius,external_baseline,greedy_kcenter,1,150.088443,150.088443,128.464033,163.655660,0.000960,1.0,0.0
8,radius,external_baseline,python_kmedoids_fasterpam,1,54.775943,54.775943,45.598467,71.580189,0.820236,1.0,0.0
9,radius,external_baseline,python_kmedoids_pam,1,68.160377,68.160377,68.160377,68.160377,0.950344,1.0,0.0
10,radius,external_baseline,sklearn_bisecting_kmeans,1,NaN,NaN,NaN,NaN,0.920079,1.0,0.0
11,radius,external_baseline,sklearn_kmeans_ninit20,1,NaN,NaN,NaN,NaN,0.946652,1.0,0.0
12,radius,external_baseline,sklearn_minibatch_kmeans,1,NaN,NaN,NaN,NaN,0.909346,1.0,0.0
13,radius,llm_selected,01_20260517_215015_candidate_042_best_final_qu...,1,30.439269,30.439269,30.439269,30.439269,17.101252,1.0,0.0
14,radius,llm_selected,01_candidate_031_recursive_sphere_covering,1,NaN,NaN,NaN,NaN,0.085093,1.0,0.0
15,radius,llm_selected,02_20260517_215015_candidate_031_speed_quality...,1,46.609670,46.609670,46.609670,46.609670,5.119868,1.0,0.0
16,radius,llm_selected,02_candidate_035_recursive_sphere_covering_var...,1,NaN,NaN,NaN,NaN,0.101076,1.0,0.0
17,radius,llm_selected,03_20260518_181812_candidate_004_hybrid_sampli...,1,39.711085,39.711085,39.711085,39.711085,1.640734,1.0,0.0
18,radius,llm_selected,03_candidate_004_sampling_50p_full_valid,1,NaN,NaN,NaN,NaN,0.044447,1.0,0.0
19,radius,llm_selected,04_20260518_181812_candidate_006_hybrid_sampli...,1,58.785377,58.785377,58.785377,58.785377,1.518543,1.0,0.0
20,radius,llm_selected,04_candidate_007_sampling_50p_best_gap,1,NaN,NaN,NaN,NaN,0.058871,1.0,0.0
21,radius,llm_selected,05_20260518_162854_candidate_020_fast_sample_b...,1,43.012972,43.012972,43.012972,43.012972,0.014802,1.0,0.0
22,radius,llm_selected,05_candidate_008_sampling_20p_fast_broad,1,NaN,NaN,NaN,NaN,0.018598,1.0,0.0
23,radius,llm_selected,06_20260517_191550_candidate_014_cluster_split...,1,135.642689,135.642689,135.642689,135.642689,1.263216,1.0,0.0
24,radius,llm_selected,06_VolumeCovering_V5,1,NaN,NaN,NaN,NaN,0.147770,1.0,0.0
25,radius,llm_selected,07_20260518_080147_candidate_008_dynamic_radiu...,1,119.737618,119.737618,119.737618,119.737618,0.543866,1.0,0.0
26,radius,taillard_cpp,taillard_cpp_hybrid_10p,1,21.071500,21.071500,10.546500,46.936900,0.087566,1.0,0.0
27,radius,taillard_cpp,taillard_cpp_kmedian,1,58.992000,58.992000,29.988200,83.415400,0.000786,1.0,0.0
28,radius,taillard_cpp,taillard_cpp_pam,1,21.550500,21.550500,5.718300,39.840500,0.423398,1.0,0.0
29,sse,external_baseline,sklearn_bisecting_kmeans,1,NaN,NaN,NaN,NaN,0.934057,1.0,0.0

 instance_summary.csv -> OK

,objective,method_group,method_id,instance,n,p,d,instance_id,objective_value_count,objective_value_median,...,quality_ratio_median,quality_ratio_mean,quality_ratio_p10,quality_ratio_p90,attempts,successes,timeouts,invalid_or_error,success_rate,timeout_rate
0,pmedian,external_baseline,python_kmedoids_fasterpam,cluster_tai00400_020_2_0,400,20,2,0,10,4724.976082,...,NaN,NaN,NaN,NaN,10,10,0,0,1.0,0.0
1,pmedian,external_baseline,python_kmedoids_pam,cluster_tai00400_020_2_0,400,20,2,0,10,4743.702413,...,NaN,NaN,NaN,NaN,10,10,0,0,1.0,0.0
2,pmedian,llm_selected,01_candidate_006_best_valid_nucleation,cluster_tai00400_020_2_0,400,20,2,0,1,5571.750548,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
3,pmedian,llm_selected,02_candidate_007_best_raw_nucleation,cluster_tai00400_020_2_0,400,20,2,0,1,5487.263255,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
4,pmedian,llm_selected,03_ImprovedPMedianHeuristic4,cluster_tai00400_020_2_0,400,20,2,0,1,5012.249408,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
5,pmedian,llm_selected,04_candidate_027_sampling_10p_quality,cluster_tai00400_020_2_0,400,20,2,0,1,4830.528606,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
6,pmedian,llm_selected,05_candidate_023_sampling_10p_fast,cluster_tai00400_020_2_0,400,20,2,0,1,4965.769919,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
7,radius,external_baseline,greedy_kcenter,cluster_tai00400_020_2_0,400,20,2,0,30,16966.000000,...,2.500884,2.488419,2.284640,2.636557,30,30,0,0,1.0,0.0
8,radius,external_baseline,python_kmedoids_fasterpam,cluster_tai00400_020_2_0,400,20,2,0,10,10500.000000,...,1.547759,1.566141,1.455985,1.715802,10,10,0,0,1.0,0.0
9,radius,external_baseline,python_kmedoids_pam,cluster_tai00400_020_2_0,400,20,2,0,10,11408.000000,...,1.681604,1.681604,1.681604,1.681604,10,10,0,0,1.0,0.0
10,radius,external_baseline,sklearn_bisecting_kmeans,cluster_tai00400_020_2_0,400,20,2,0,30,9338.909642,...,NaN,NaN,NaN,NaN,30,30,0,0,1.0,0.0
11,radius,external_baseline,sklearn_kmeans_ninit20,cluster_tai00400_020_2_0,400,20,2,0,30,8660.096478,...,NaN,NaN,NaN,NaN,30,30,0,0,1.0,0.0
12,radius,external_baseline,sklearn_minibatch_kmeans,cluster_tai00400_020_2_0,400,20,2,0,30,9077.697685,...,NaN,NaN,NaN,NaN,30,30,0,0,1.0,0.0
13,radius,llm_selected,01_20260517_215015_candidate_042_best_final_qu...,cluster_tai00400_020_2_0,400,20,2,0,1,8849.000000,...,1.304393,1.304393,1.304393,1.304393,1,1,0,0,1.0,0.0
14,radius,llm_selected,01_candidate_031_recursive_sphere_covering,cluster_tai00400_020_2_0,400,20,2,0,1,7795.846059,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
15,radius,llm_selected,02_20260517_215015_candidate_031_speed_quality...,cluster_tai00400_020_2_0,400,20,2,0,1,9946.000000,...,1.466097,1.466097,1.466097,1.466097,1,1,0,0,1.0,0.0
16,radius,llm_selected,02_candidate_035_recursive_sphere_covering_var...,cluster_tai00400_020_2_0,400,20,2,0,1,7795.846059,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
17,radius,llm_selected,03_20260518_181812_candidate_004_hybrid_sampli...,cluster_tai00400_020_2_0,400,20,2,0,1,9478.000000,...,1.397111,1.397111,1.397111,1.397111,1,1,0,0,1.0,0.0
18,radius,llm_selected,03_candidate_004_sampling_50p_full_valid,cluster_tai00400_020_2_0,400,20,2,0,1,8874.598197,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
19,radius,llm_selected,04_20260518_181812_candidate_006_hybrid_sampli...,cluster_tai00400_020_2_0,400,20,2,0,1,10772.000000,...,1.587854,1.587854,1.587854,1.587854,1,1,0,0,1.0,0.0
20,radius,llm_selected,04_candidate_007_sampling_50p_best_gap,cluster_tai00400_020_2_0,400,20,2,0,1,9488.426107,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
21,radius,llm_selected,05_20260518_162854_candidate_020_fast_sample_b...,cluster_tai00400_020_2_0,400,20,2,0,1,9702.000000,...,1.430130,1.430130,1.430130,1.430130,1,1,0,0,1.0,0.0
22,radius,llm_selected,05_candidate_008_sampling_20p_fast_broad,cluster_tai00400_020_2_0,400,20,2,0,1,8670.378450,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
23,radius,llm_selected,06_20260517_191550_candidate_014_cluster_split...,cluster_tai00400_020_2_0,400,20,2,0,1,15986.000000,...,2.356427,2.356427,2.356427,2.356427,1,1,0,0,1.0,0.0
24,radius,llm_selected,06_VolumeCovering_V5,cluster_tai00400_020_2_0,400,20,2,0,1,11296.163930,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
25,radius,llm_selected,07_20260518_080147_candidate_008_dynamic_radiu...,cluster_tai00400_020_2_0,400,20,2,0,1,14907.000000,...,2.197376,2.197376,2.197376,2.197376,1,1,0,0,1.0,0.0
26,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,400,20,2,0,30,8213.490560,...,1.210715,1.251169,1.105465,1.469369,30,30,0,0,1.0,0.0
27,radius,taillard_cpp,taillard_cpp_kmedian,cluster_tai00400_020_2_0,400,20,2,0,30,10786.017280,...,1.589920,1.579388,1.299882,1.834154,30,30,0,0,1.0,0.0
28,radius,taillard_cpp,taillard_cpp_pam,cluster_tai00400_020_2_0,400,20,2,0,30,8245.985920,...,1.215505,1.223624,1.057183,1.398405,30,30,0,0,1.0,0.0
29,sse,external_baseline,sklearn_bisecting_kmeans,cluster_tai00400_020_2_0,400,20,2,0,30,70317.305484,...,NaN,NaN,NaN,NaN,30,30,0,0,1.0,0.0

 complexity_fit.csv -> OK
CSV exists but has no parseable columns. Usually means no data was available for this summary.

 complexity_fit_points.csv -> missing

 center_repair_warning_counts.json -> OK
{
  "snapped_to_points": 82
}

No complexity_plots directory yet.

Artifact zip: /content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1.zip exists= True

## 8. Read live progress / checkpoint summaries

In [38]:
import json
from pathlib import Path
import pandas as pd

artifact_dir = Path(ARTIFACT_DIR + ("_smoke" if SMOKE_TEST else ""))
progress_file = artifact_dir / "progress_state.json"
checkpoint_file = artifact_dir / "raw_runs_checkpoint.csv"

if progress_file.exists():
    print(json.dumps(json.loads(progress_file.read_text()), indent=2))
else:
    print("No progress_state.json yet:", progress_file)

if checkpoint_file.exists():
    df = pd.read_csv(checkpoint_file)
    print("\nCheckpoint rows:", len(df))
    display(df.tail(20))
    print("\nSuccess/timeout by objective/method:")
    display(df.groupby(["objective", "method_id"]).agg(rows=("success", "count"), success_rate=("success", "mean"), timeout_rate=("timeout", "mean")).reset_index().tail(50))
else:
    print("No checkpoint yet:", checkpoint_file)

{
  "status": "finished_or_stopped",
  "artifact_dir": "/content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1",
  "planned_jobs": 443,
  "completed_jobs": 443,
  "new_jobs_this_process": 443,
  "raw_runs_checkpoint": "/content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1/raw_runs_checkpoint.csv",
  "updated_at": "2026-05-21T14:48:49"
}

Checkpoint rows: 443

,objective,method_group,method_type,method_id,method_path,method_variant,center_constraint,reference_key,instance,n,...,gap_pct,center_status,center_note,warning,error,cpp_reference_time_s,cpp_reference_pam_ratio,cpp_reference_pam_time_s,cpp_wall_runtime_s,cpp_best_improvement_events
423,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,18.219,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000116,0.938827,0.412774,0.506777,0.0
424,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,10.938,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000076,0.938827,0.374733,0.476784,0.0
425,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,34.596,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000121,0.938827,0.377390,0.484336,0.0
426,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,22.789,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000108,0.938827,0.421318,0.526330,0.0
427,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,18.440,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000112,0.938827,0.374433,0.464755,0.0
428,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,8.269,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000132,0.938827,0.381928,0.477756,0.0
429,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,34.169,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000089,0.938827,0.380354,0.474467,0.0
430,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,9.552,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000094,0.938827,0.409520,0.504474,0.0
431,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,18.794,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000129,0.938827,0.376712,0.466431,0.0
432,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,19.354,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000113,0.938827,0.602969,0.739121,0.0
433,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,22.848,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000119,0.938827,0.610691,0.757713,0.0
434,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,15.492,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000120,0.938827,0.578152,0.718279,0.0
435,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,25.575,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000116,0.938827,0.594389,0.746583,0.0
436,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,17.468,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000128,0.938827,0.640563,0.795061,0.0
437,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,14.431,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000119,0.938827,0.394779,0.498786,0.0
438,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,23.835,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000114,0.938827,0.400099,0.494972,0.0
439,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,33.476,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000105,0.938827,0.448326,0.542004,0.0
440,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,61.232,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000121,0.938827,0.388191,0.498472,0.0
441,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,25.884,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000115,0.938827,0.425150,0.519095,0.0
442,radius,taillard_cpp,taillard_cpp,taillard_cpp_hybrid_10p,NaN,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,34.154,cpp_direct_output_no_centers,Taillard C++ program reports ratio/value/time ...,NaN,NaN,0.000108,0.938827,0.419320,0.511624,0.0

Success/timeout by objective/method:

,objective,method_id,rows,success_rate,timeout_rate
0,pmedian,01_candidate_006_best_valid_nucleation,1,1.0,0.0
1,pmedian,02_candidate_007_best_raw_nucleation,1,1.0,0.0
2,pmedian,03_ImprovedPMedianHeuristic4,1,1.0,0.0
3,pmedian,04_candidate_027_sampling_10p_quality,1,1.0,0.0
4,pmedian,05_candidate_023_sampling_10p_fast,1,1.0,0.0
5,pmedian,python_kmedoids_fasterpam,10,1.0,0.0
6,pmedian,python_kmedoids_fastpam,10,0.0,0.0
7,pmedian,python_kmedoids_pam,10,1.0,0.0
8,pmedian,sklearn_extra_clara,30,0.0,0.0
9,radius,01_20260517_215015_candidate_042_best_final_qu...,1,1.0,0.0
10,radius,01_candidate_031_recursive_sphere_covering,1,1.0,0.0
11,radius,02_20260517_215015_candidate_031_speed_quality...,1,1.0,0.0
12,radius,02_candidate_035_recursive_sphere_covering_var...,1,1.0,0.0
13,radius,03_20260518_181812_candidate_004_hybrid_sampli...,1,1.0,0.0
14,radius,03_candidate_004_sampling_50p_full_valid,1,1.0,0.0
15,radius,04_20260518_181812_candidate_006_hybrid_sampli...,1,1.0,0.0
16,radius,04_candidate_007_sampling_50p_best_gap,1,1.0,0.0
17,radius,05_20260518_162854_candidate_020_fast_sample_b...,1,1.0,0.0
18,radius,05_candidate_008_sampling_20p_fast_broad,1,1.0,0.0
19,radius,06_20260517_191550_candidate_014_cluster_split...,1,1.0,0.0
20,radius,06_VolumeCovering_V5,1,1.0,0.0
21,radius,07_20260518_080147_candidate_008_dynamic_radiu...,1,1.0,0.0
22,radius,greedy_kcenter,30,1.0,0.0
23,radius,python_kmedoids_fasterpam,10,1.0,0.0
24,radius,python_kmedoids_fastpam,10,0.0,0.0
25,radius,python_kmedoids_pam,10,1.0,0.0
26,radius,sklearn_bisecting_kmeans,30,1.0,0.0
27,radius,sklearn_extra_clara,30,0.0,0.0
28,radius,sklearn_kmeans_ninit20,30,1.0,0.0
29,radius,sklearn_minibatch_kmeans,30,1.0,0.0
30,radius,taillard_cpp_hybrid_10p,30,1.0,0.0
31,radius,taillard_cpp_kmedian,30,1.0,0.0
32,radius,taillard_cpp_pam,30,1.0,0.0
33,sse,01_candidate_037_best_quality,1,1.0,0.0
34,sse,02_candidate_028_same_run_faster,1,1.0,0.0
35,sse,03_candidate_028_edited_noise_injection,1,1.0,0.0
36,sse,04_candidate_013_gradient_momentum,1,1.0,0.0
37,sse,05_candidate_006_sampling_60p,1,1.0,0.0
38,sse,sklearn_bisecting_kmeans,30,1.0,0.0
39,sse,sklearn_kmeans_ninit20,30,1.0,0.0
40,sse,sklearn_minibatch_kmeans,30,1.0,0.0

## 9. Inspect final summaries and complexity plots

In [40]:
from pathlib import Path
import pandas as pd
from pandas.errors import EmptyDataError
from IPython.display import display, Image
import shutil
import os
import time

# ============================================================
# Artifact inspection + local download
# ============================================================

DOWNLOAD_TO_PC = True   # Set False if you only want to inspect, not download.
FORCE_REZIP = True      # True = recreate the zip from the artifact folder.

artifact_dir = Path(ARTIFACT_DIR + ("_smoke" if SMOKE_TEST else ""))
print("Artifact directory:", artifact_dir)
print("Exists:", artifact_dir.exists())

if not artifact_dir.exists():
    raise FileNotFoundError(f"Artifact directory not found: {artifact_dir}")

# ------------------------------------------------------------
# Display key summary files
# ------------------------------------------------------------
for name in [
    "method_manifest.csv",
    "raw_runs.csv",
    "method_summary.csv",
    "instance_summary.csv",
    "complexity_fit.csv",
    "complexity_fit_points.csv",
    "center_repair_warning_counts.json",
]:
    p = artifact_dir / name
    print("\n", name, "->", "OK" if p.exists() else "missing")

    if not p.exists():
        continue

    if p.suffix == ".csv":
        if p.stat().st_size == 0:
            print("File exists but is empty. This is normal if there are not enough data points yet.")
            continue

        try:
            df = pd.read_csv(p)
            print("shape:", df.shape)
            if df.empty:
                print("CSV has columns but no rows.")
            else:
                display(df.head(30))
        except EmptyDataError:
            print("CSV exists but has no parseable columns. Usually means no data was available for this summary.")
    else:
        print(p.read_text(encoding="utf-8", errors="ignore")[:2000])

# ------------------------------------------------------------
# Display complexity plots if available
# ------------------------------------------------------------
plot_dir = artifact_dir / "complexity_plots"
if plot_dir.exists():
    pngs = sorted(plot_dir.glob("*.png"))
    if not pngs:
        print("\ncomplexity_plots exists but contains no PNG yet.")
    for png in pngs[:20]:
        print("\n", png.name)
        display(Image(filename=str(png)))
    if len(pngs) > 20:
        print(f"\nOnly displayed first 20 plots out of {len(pngs)}.")
else:
    print("\nNo complexity_plots directory yet.")

# ------------------------------------------------------------
# Create/recreate artifact zip
# ------------------------------------------------------------
zip_path = Path(str(artifact_dir) + ".zip")

if FORCE_REZIP or not zip_path.exists():
    if zip_path.exists():
        print("\nRemoving old zip:", zip_path)
        zip_path.unlink()

    print("\nCreating artifact zip. This may take time for a large run...")
    base_name = str(artifact_dir)
    root_dir = str(artifact_dir.parent)
    base_dir = artifact_dir.name

    created_zip = shutil.make_archive(
        base_name=base_name,
        format="zip",
        root_dir=root_dir,
        base_dir=base_dir,
    )
    zip_path = Path(created_zip)

print("\nArtifact zip:", zip_path)
print("Zip exists:", zip_path.exists())
print("Zip size MB:", round(zip_path.stat().st_size / (1024 * 1024), 2))

# ------------------------------------------------------------
# Download to local PC through browser
# ------------------------------------------------------------
if DOWNLOAD_TO_PC:
    try:
        from google.colab import files

        print("\nStarting browser download to your local PC...")
        print("If the zip is very large, the download may take a while or the browser may ask for confirmation.")

        files.download(str(zip_path))

        print("\nDownload command sent to browser.")
    except Exception as e:
        print("\nCould not trigger Colab browser download automatically.")
        print("Error:", repr(e))
        print("Your zip is still saved here:")
        print(zip_path)
else:
    print("\nDOWNLOAD_TO_PC=False, so no local browser download was triggered.")

Artifact directory: /content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1
Exists: True

 method_manifest.csv -> OK
shape: (41, 14)

,method_id,method_group,method_type,objective,center_constraint,method_variant,reference_key,path,relative_path,info_text,params,max_n,repetitions,cpp_option
0,01_candidate_006_best_valid_nucleation,llm_selected,python,pmedian,snap_to_points,pmedian_data_point,pmedian,experiments/selected_clustering_heuristics_fin...,P_MEDIAN_data_point_centers/01_candidate_006_b...,p-median candidate 6\n\nObjective folder: P_ME...,NaN,NaN,NaN,NaN
1,02_candidate_007_best_raw_nucleation,llm_selected,python,pmedian,snap_to_points,pmedian_data_point,pmedian,experiments/selected_clustering_heuristics_fin...,P_MEDIAN_data_point_centers/02_candidate_007_b...,p-median candidate 7\n\nObjective folder: P_ME...,NaN,NaN,NaN,NaN
2,03_ImprovedPMedianHeuristic4,llm_selected,python,pmedian,snap_to_points,pmedian_data_point,pmedian,experiments/selected_clustering_heuristics_fin...,P_MEDIAN_data_point_centers/03_ImprovedPMedian...,ImprovedPMedianHeuristic4\n\nObjective folder:...,NaN,NaN,NaN,NaN
3,04_candidate_027_sampling_10p_quality,llm_selected,python,pmedian,snap_to_points,pmedian_data_point,pmedian,experiments/selected_clustering_heuristics_fin...,P_MEDIAN_data_point_centers/04_candidate_027_s...,p-median sampling candidate 27\n\nObjective fo...,NaN,NaN,NaN,NaN
4,05_candidate_023_sampling_10p_fast,llm_selected,python,pmedian,snap_to_points,pmedian_data_point,pmedian,experiments/selected_clustering_heuristics_fin...,P_MEDIAN_data_point_centers/05_candidate_023_s...,p-median sampling candidate 23\n\nObjective fo...,NaN,NaN,NaN,NaN
5,01_20260517_215015_candidate_042_best_final_qu...,llm_selected,python,radius,snap_to_points,radius_data_point,radius_data_point,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_data_point_centers/01_20260517_2...,20260517_215015 candidate 42\n\nObjective fold...,NaN,NaN,NaN,NaN
6,02_20260517_215015_candidate_031_speed_quality...,llm_selected,python,radius,snap_to_points,radius_data_point,radius_data_point,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_data_point_centers/02_20260517_2...,20260517_215015 candidate 31\n\nObjective fold...,NaN,NaN,NaN,NaN
7,03_20260518_181812_candidate_004_hybrid_sampli...,llm_selected,python,radius,snap_to_points,radius_data_point,radius_data_point,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_data_point_centers/03_20260518_1...,20260518_181812 candidate 4\n\nObjective folde...,NaN,NaN,NaN,NaN
8,04_20260518_181812_candidate_006_hybrid_sampli...,llm_selected,python,radius,snap_to_points,radius_data_point,radius_data_point,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_data_point_centers/04_20260518_1...,20260518_181812 candidate 6\n\nObjective folde...,NaN,NaN,NaN,NaN
9,05_20260518_162854_candidate_020_fast_sample_b...,llm_selected,python,radius,snap_to_points,radius_data_point,radius_data_point,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_data_point_centers/05_20260518_1...,20260518_162854 candidate 20\n\nObjective fold...,NaN,NaN,NaN,NaN
10,06_20260517_191550_candidate_014_cluster_split...,llm_selected,python,radius,snap_to_points,radius_data_point,radius_data_point,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_data_point_centers/06_20260517_1...,20260517_191550 candidate 14\n\nObjective fold...,NaN,NaN,NaN,NaN
11,07_20260518_080147_candidate_008_dynamic_radiu...,llm_selected,python,radius,snap_to_points,radius_data_point,radius_data_point,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_data_point_centers/07_20260518_0...,20260518_080147 candidate 8\n\nObjective folde...,NaN,NaN,NaN,NaN
12,01_candidate_031_recursive_sphere_covering,llm_selected,python,radius,free,radius_free,radius_free,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_free_centers/01_candidate_031_re...,radius recursive sphere-covering candidate 31\...,NaN,NaN,NaN,NaN
13,02_candidate_035_recursive_sphere_covering_var...,llm_selected,python,radius,free,radius_free,radius_free,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_free_centers/02_candidate_035_re...,radius recursive sphere-covering candidate 35\...,NaN,NaN,NaN,NaN
14,03_candidate_004_sampling_50p_full_valid,llm_selected,python,radius,free,radius_free,radius_free,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_free_centers/03_candidate_004_sa...,radius sample_50p candidate 4\n\nObjective fol...,NaN,NaN,NaN,NaN
15,04_candidate_007_sampling_50p_best_gap,llm_selected,python,radius,free,radius_free,radius_free,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_free_centers/04_candidate_007_sa...,radius sample_50p candidate 7\n\nObjective fol...,NaN,NaN,NaN,NaN
16,05_candidate_008_sampling_20p_fast_broad,llm_selected,python,radius,free,radius_free,radius_free,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_free_centers/05_candidate_008_sa...,radius sampling 20p candidate 8\n\nObjective f...,NaN,NaN,NaN,NaN
17,06_VolumeCovering_V5,llm_selected,python,radius,free,radius_free,radius_free,experiments/selected_clustering_heuristics_fin...,RADIUS_VOLUME_free_centers/06_VolumeCovering_V...,VolumeCovering V5\n\nObjective folder: RADIUS_...,NaN,NaN,NaN,NaN
18,01_candidate_037_best_quality,llm_selected,python,sse,free,sse_free,sse,experiments/selected_clustering_heuristics_fin...,SSE_free_centers/01_candidate_037_best_quality...,SSE candidate 37\n\nObjective folder: SSE_free...,NaN,NaN,NaN,NaN
19,02_candidate_028_same_run_faster,llm_selected,python,sse,free,sse_free,sse,experiments/selected_clustering_heuristics_fin...,SSE_free_centers/02_candidate_028_same_run_fas...,"SSE candidate 28, same run\n\nObjective folder...",NaN,NaN,NaN,NaN
20,03_candidate_028_edited_noise_injection,llm_selected,python,sse,free,sse_free,sse,experiments/selected_clustering_heuristics_fin...,SSE_free_centers/03_candidate_028_edited_noise...,SSE edited candidate 28\n\nObjective folder: S...,NaN,NaN,NaN,NaN
21,04_candidate_013_gradient_momentum,llm_selected,python,sse,free,sse_free,sse,experiments/selected_clustering_heuristics_fin...,SSE_free_centers/04_candidate_013_gradient_mom...,SSE gradient/momentum candidate 13\n\nObjectiv...,NaN,NaN,NaN,NaN
22,05_candidate_006_sampling_60p,llm_selected,python,sse,free,sse_free,sse,experiments/selected_clustering_heuristics_fin...,SSE_free_centers/05_candidate_006_sampling_60p...,SSE sampling 60p candidate 6\n\nObjective fold...,NaN,NaN,NaN,NaN
23,sklearn_kmeans_ninit20,external_baseline,python,radius,NaN,radius_free,radius_free,NaN,NaN,NaN,{'n_init': 20},NaN,30.0,NaN
24,sklearn_kmeans_ninit20,external_baseline,python,sse,NaN,sse,sse,NaN,NaN,NaN,{'n_init': 20},NaN,30.0,NaN
25,sklearn_minibatch_kmeans,external_baseline,python,radius,NaN,radius_free,radius_free,NaN,NaN,NaN,{'n_init': 10},NaN,30.0,NaN
26,sklearn_minibatch_kmeans,external_baseline,python,sse,NaN,sse,sse,NaN,NaN,NaN,{'n_init': 10},NaN,30.0,NaN
27,sklearn_bisecting_kmeans,external_baseline,python,radius,NaN,radius_free,radius_free,NaN,NaN,NaN,{'n_init': 5},NaN,30.0,NaN
28,sklearn_bisecting_kmeans,external_baseline,python,sse,NaN,sse,sse,NaN,NaN,NaN,{'n_init': 5},NaN,30.0,NaN
29,python_kmedoids_pam,external_baseline,python,pmedian,snap_to_points,pmedian,pmedian,NaN,NaN,NaN,{},NaN,10.0,NaN

 raw_runs.csv -> OK
shape: (443, 31)

,objective,method_group,method_type,method_id,method_path,method_variant,center_constraint,reference_key,instance,n,...,gap_pct,center_status,center_note,warning,error,cpp_reference_time_s,cpp_reference_pam_ratio,cpp_reference_pam_time_s,cpp_wall_runtime_s,cpp_best_improvement_events
0,pmedian,llm_selected,python,01_candidate_006_best_valid_nucleation,P_MEDIAN_data_point_centers/01_candidate_006_b...,pmedian_data_point,snap_to_points,pmedian,cluster_tai00400_020_2_0,400,...,NaN,snapped_to_points,centers snapped to nearest data points for thi...,CENTER_REPAIR: pmedian 01_candidate_006_best_v...,NaN,NaN,NaN,NaN,NaN,NaN
1,pmedian,llm_selected,python,02_candidate_007_best_raw_nucleation,P_MEDIAN_data_point_centers/02_candidate_007_b...,pmedian_data_point,snap_to_points,pmedian,cluster_tai00400_020_2_0,400,...,NaN,snapped_to_points,centers snapped to nearest data points for thi...,CENTER_REPAIR: pmedian 02_candidate_007_best_r...,NaN,NaN,NaN,NaN,NaN,NaN
2,pmedian,llm_selected,python,03_ImprovedPMedianHeuristic4,P_MEDIAN_data_point_centers/03_ImprovedPMedian...,pmedian_data_point,snap_to_points,pmedian,cluster_tai00400_020_2_0,400,...,NaN,snapped_to_points,centers snapped to nearest data points for thi...,CENTER_REPAIR: pmedian 03_ImprovedPMedianHeuri...,NaN,NaN,NaN,NaN,NaN,NaN
3,pmedian,llm_selected,python,04_candidate_027_sampling_10p_quality,P_MEDIAN_data_point_centers/04_candidate_027_s...,pmedian_data_point,snap_to_points,pmedian,cluster_tai00400_020_2_0,400,...,NaN,snapped_to_points,centers snapped to nearest data points for thi...,CENTER_REPAIR: pmedian 04_candidate_027_sampli...,NaN,NaN,NaN,NaN,NaN,NaN
4,pmedian,llm_selected,python,05_candidate_023_sampling_10p_fast,P_MEDIAN_data_point_centers/05_candidate_023_s...,pmedian_data_point,snap_to_points,pmedian,cluster_tai00400_020_2_0,400,...,NaN,snapped_to_points,centers snapped to nearest data points for thi...,CENTER_REPAIR: pmedian 05_candidate_023_sampli...,NaN,NaN,NaN,NaN,NaN,NaN
5,radius,llm_selected,python,01_20260517_215015_candidate_042_best_final_qu...,RADIUS_VOLUME_data_point_centers/01_20260517_2...,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,30.439269,snapped_to_points,centers snapped to nearest data points for thi...,CENTER_REPAIR: radius 01_20260517_215015_candi...,NaN,NaN,NaN,NaN,NaN,NaN
6,radius,llm_selected,python,02_20260517_215015_candidate_031_speed_quality...,RADIUS_VOLUME_data_point_centers/02_20260517_2...,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,46.609670,snapped_to_points,centers snapped to nearest data points for thi...,CENTER_REPAIR: radius 02_20260517_215015_candi...,NaN,NaN,NaN,NaN,NaN,NaN
7,radius,llm_selected,python,03_20260518_181812_candidate_004_hybrid_sampli...,RADIUS_VOLUME_data_point_centers/03_20260518_1...,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,39.711085,snapped_to_points,centers snapped to nearest data points for thi...,CENTER_REPAIR: radius 03_20260518_181812_candi...,NaN,NaN,NaN,NaN,NaN,NaN
8,radius,llm_selected,python,04_20260518_181812_candidate_006_hybrid_sampli...,RADIUS_VOLUME_data_point_centers/04_20260518_1...,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,58.785377,snapped_to_points,centers snapped to nearest data points for thi...,CENTER_REPAIR: radius 04_20260518_181812_candi...,NaN,NaN,NaN,NaN,NaN,NaN
9,radius,llm_selected,python,05_20260518_162854_candidate_020_fast_sample_b...,RADIUS_VOLUME_data_point_centers/05_20260518_1...,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,43.012972,snapped_to_points,centers snapped to nearest data points for thi...,CENTER_REPAIR: radius 05_20260518_162854_candi...,NaN,NaN,NaN,NaN,NaN,NaN
10,radius,llm_selected,python,06_20260517_191550_candidate_014_cluster_split...,RADIUS_VOLUME_data_point_centers/06_20260517_1...,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,135.642689,snapped_to_points,centers snapped to nearest data points for thi...,CENTER_REPAIR: radius 06_20260517_191550_candi...,NaN,NaN,NaN,NaN,NaN,NaN
11,radius,llm_selected,python,07_20260518_080147_candidate_008_dynamic_radiu...,RADIUS_VOLUME_data_point_centers/07_20260518_0...,radius_data_point,snap_to_points,radius_data_point,cluster_tai00400_020_2_0,400,...,119.737618,snapped_to_points,centers snapped to nearest data points for thi...,CENTER_REPAIR: radius 07_20260518_080147_candi...,NaN,NaN,NaN,NaN,NaN,NaN
12,radius,llm_selected,python,01_candidate_031_recursive_sphere_covering,RADIUS_VOLUME_free_centers/01_candidate_031_re...,radius_free,free,radius_free,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,radius,llm_selected,python,02_candidate_035_recursive_sphere_covering_var...,RADIUS_VOLUME_free_centers/02_candidate_035_re...,radius_free,free,radius_free,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,radius,llm_selected,python,03_candidate_004_sampling_50p_full_valid,RADIUS_VOLUME_free_centers/03_candidate_004_sa...,radius_free,free,radius_free,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,radius,llm_selected,python,04_candidate_007_sampling_50p_best_gap,RADIUS_VOLUME_free_centers/04_candidate_007_sa...,radius_free,free,radius_free,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,radius,llm_selected,python,05_candidate_008_sampling_20p_fast_broad,RADIUS_VOLUME_free_centers/05_candidate_008_sa...,radius_free,free,radius_free,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,radius,llm_selected,python,06_VolumeCovering_V5,RADIUS_VOLUME_free_centers/06_VolumeCovering_V...,radius_free,free,radius_free,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,sse,llm_selected,python,01_candidate_037_best_quality,SSE_free_centers/01_candidate_037_best_quality...,sse_free,free,sse,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,sse,llm_selected,python,02_candidate_028_same_run_faster,SSE_free_centers/02_candidate_028_same_run_fas...,sse_free,free,sse,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,sse,llm_selected,python,03_candidate_028_edited_noise_injection,SSE_free_centers/03_candidate_028_edited_noise...,sse_free,free,sse,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,sse,llm_selected,python,04_candidate_013_gradient_momentum,SSE_free_centers/04_candidate_013_gradient_mom...,sse_free,free,sse,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,sse,llm_selected,python,05_candidate_006_sampling_60p,SSE_free_centers/05_candidate_006_sampling_60p...,sse_free,free,sse,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,radius,external_baseline,python,sklearn_kmeans_ninit20,NaN,radius_free,NaN,radius_free,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,radius,external_baseline,python,sklearn_kmeans_ninit20,NaN,radius_free,NaN,radius_free,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,radius,external_baseline,python,sklearn_kmeans_ninit20,NaN,radius_free,NaN,radius_free,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,radius,external_baseline,python,sklearn_kmeans_ninit20,NaN,radius_free,NaN,radius_free,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,radius,external_baseline,python,sklearn_kmeans_ninit20,NaN,radius_free,NaN,radius_free,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,radius,external_baseline,python,sklearn_kmeans_ninit20,NaN,radius_free,NaN,radius_free,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,radius,external_baseline,python,sklearn_kmeans_ninit20,NaN,radius_free,NaN,radius_free,cluster_tai00400_020_2_0,400,...,NaN,ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

 method_summary.csv -> OK
shape: (37, 11)

,objective,method_group,method_id,instances,median_gap_over_instances,mean_gap_over_instances,p10_gap_over_instances,p90_gap_over_instances,median_runtime_over_instances,success_rate_mean,timeout_rate_mean
0,pmedian,external_baseline,python_kmedoids_fasterpam,1,NaN,NaN,NaN,NaN,0.840772,1.0,0.0
1,pmedian,external_baseline,python_kmedoids_pam,1,NaN,NaN,NaN,NaN,0.935365,1.0,0.0
2,pmedian,llm_selected,01_candidate_006_best_valid_nucleation,1,NaN,NaN,NaN,NaN,0.145281,1.0,0.0
3,pmedian,llm_selected,02_candidate_007_best_raw_nucleation,1,NaN,NaN,NaN,NaN,0.259777,1.0,0.0
4,pmedian,llm_selected,03_ImprovedPMedianHeuristic4,1,NaN,NaN,NaN,NaN,0.023769,1.0,0.0
5,pmedian,llm_selected,04_candidate_027_sampling_10p_quality,1,NaN,NaN,NaN,NaN,0.028451,1.0,0.0
6,pmedian,llm_selected,05_candidate_023_sampling_10p_fast,1,NaN,NaN,NaN,NaN,0.013696,1.0,0.0
7,radius,external_baseline,greedy_kcenter,1,150.088443,150.088443,128.464033,163.655660,0.000960,1.0,0.0
8,radius,external_baseline,python_kmedoids_fasterpam,1,54.775943,54.775943,45.598467,71.580189,0.820236,1.0,0.0
9,radius,external_baseline,python_kmedoids_pam,1,68.160377,68.160377,68.160377,68.160377,0.950344,1.0,0.0
10,radius,external_baseline,sklearn_bisecting_kmeans,1,NaN,NaN,NaN,NaN,0.920079,1.0,0.0
11,radius,external_baseline,sklearn_kmeans_ninit20,1,NaN,NaN,NaN,NaN,0.946652,1.0,0.0
12,radius,external_baseline,sklearn_minibatch_kmeans,1,NaN,NaN,NaN,NaN,0.909346,1.0,0.0
13,radius,llm_selected,01_20260517_215015_candidate_042_best_final_qu...,1,30.439269,30.439269,30.439269,30.439269,17.101252,1.0,0.0
14,radius,llm_selected,01_candidate_031_recursive_sphere_covering,1,NaN,NaN,NaN,NaN,0.085093,1.0,0.0
15,radius,llm_selected,02_20260517_215015_candidate_031_speed_quality...,1,46.609670,46.609670,46.609670,46.609670,5.119868,1.0,0.0
16,radius,llm_selected,02_candidate_035_recursive_sphere_covering_var...,1,NaN,NaN,NaN,NaN,0.101076,1.0,0.0
17,radius,llm_selected,03_20260518_181812_candidate_004_hybrid_sampli...,1,39.711085,39.711085,39.711085,39.711085,1.640734,1.0,0.0
18,radius,llm_selected,03_candidate_004_sampling_50p_full_valid,1,NaN,NaN,NaN,NaN,0.044447,1.0,0.0
19,radius,llm_selected,04_20260518_181812_candidate_006_hybrid_sampli...,1,58.785377,58.785377,58.785377,58.785377,1.518543,1.0,0.0
20,radius,llm_selected,04_candidate_007_sampling_50p_best_gap,1,NaN,NaN,NaN,NaN,0.058871,1.0,0.0
21,radius,llm_selected,05_20260518_162854_candidate_020_fast_sample_b...,1,43.012972,43.012972,43.012972,43.012972,0.014802,1.0,0.0
22,radius,llm_selected,05_candidate_008_sampling_20p_fast_broad,1,NaN,NaN,NaN,NaN,0.018598,1.0,0.0
23,radius,llm_selected,06_20260517_191550_candidate_014_cluster_split...,1,135.642689,135.642689,135.642689,135.642689,1.263216,1.0,0.0
24,radius,llm_selected,06_VolumeCovering_V5,1,NaN,NaN,NaN,NaN,0.147770,1.0,0.0
25,radius,llm_selected,07_20260518_080147_candidate_008_dynamic_radiu...,1,119.737618,119.737618,119.737618,119.737618,0.543866,1.0,0.0
26,radius,taillard_cpp,taillard_cpp_hybrid_10p,1,21.071500,21.071500,10.546500,46.936900,0.087566,1.0,0.0
27,radius,taillard_cpp,taillard_cpp_kmedian,1,58.992000,58.992000,29.988200,83.415400,0.000786,1.0,0.0
28,radius,taillard_cpp,taillard_cpp_pam,1,21.550500,21.550500,5.718300,39.840500,0.423398,1.0,0.0
29,sse,external_baseline,sklearn_bisecting_kmeans,1,NaN,NaN,NaN,NaN,0.934057,1.0,0.0

 instance_summary.csv -> OK
shape: (37, 37)

,objective,method_group,method_id,instance,n,p,d,instance_id,objective_value_count,objective_value_median,...,quality_ratio_median,quality_ratio_mean,quality_ratio_p10,quality_ratio_p90,attempts,successes,timeouts,invalid_or_error,success_rate,timeout_rate
0,pmedian,external_baseline,python_kmedoids_fasterpam,cluster_tai00400_020_2_0,400,20,2,0,10,4724.976082,...,NaN,NaN,NaN,NaN,10,10,0,0,1.0,0.0
1,pmedian,external_baseline,python_kmedoids_pam,cluster_tai00400_020_2_0,400,20,2,0,10,4743.702413,...,NaN,NaN,NaN,NaN,10,10,0,0,1.0,0.0
2,pmedian,llm_selected,01_candidate_006_best_valid_nucleation,cluster_tai00400_020_2_0,400,20,2,0,1,5571.750548,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
3,pmedian,llm_selected,02_candidate_007_best_raw_nucleation,cluster_tai00400_020_2_0,400,20,2,0,1,5487.263255,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
4,pmedian,llm_selected,03_ImprovedPMedianHeuristic4,cluster_tai00400_020_2_0,400,20,2,0,1,5012.249408,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
5,pmedian,llm_selected,04_candidate_027_sampling_10p_quality,cluster_tai00400_020_2_0,400,20,2,0,1,4830.528606,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
6,pmedian,llm_selected,05_candidate_023_sampling_10p_fast,cluster_tai00400_020_2_0,400,20,2,0,1,4965.769919,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
7,radius,external_baseline,greedy_kcenter,cluster_tai00400_020_2_0,400,20,2,0,30,16966.000000,...,2.500884,2.488419,2.284640,2.636557,30,30,0,0,1.0,0.0
8,radius,external_baseline,python_kmedoids_fasterpam,cluster_tai00400_020_2_0,400,20,2,0,10,10500.000000,...,1.547759,1.566141,1.455985,1.715802,10,10,0,0,1.0,0.0
9,radius,external_baseline,python_kmedoids_pam,cluster_tai00400_020_2_0,400,20,2,0,10,11408.000000,...,1.681604,1.681604,1.681604,1.681604,10,10,0,0,1.0,0.0
10,radius,external_baseline,sklearn_bisecting_kmeans,cluster_tai00400_020_2_0,400,20,2,0,30,9338.909642,...,NaN,NaN,NaN,NaN,30,30,0,0,1.0,0.0
11,radius,external_baseline,sklearn_kmeans_ninit20,cluster_tai00400_020_2_0,400,20,2,0,30,8660.096478,...,NaN,NaN,NaN,NaN,30,30,0,0,1.0,0.0
12,radius,external_baseline,sklearn_minibatch_kmeans,cluster_tai00400_020_2_0,400,20,2,0,30,9077.697685,...,NaN,NaN,NaN,NaN,30,30,0,0,1.0,0.0
13,radius,llm_selected,01_20260517_215015_candidate_042_best_final_qu...,cluster_tai00400_020_2_0,400,20,2,0,1,8849.000000,...,1.304393,1.304393,1.304393,1.304393,1,1,0,0,1.0,0.0
14,radius,llm_selected,01_candidate_031_recursive_sphere_covering,cluster_tai00400_020_2_0,400,20,2,0,1,7795.846059,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
15,radius,llm_selected,02_20260517_215015_candidate_031_speed_quality...,cluster_tai00400_020_2_0,400,20,2,0,1,9946.000000,...,1.466097,1.466097,1.466097,1.466097,1,1,0,0,1.0,0.0
16,radius,llm_selected,02_candidate_035_recursive_sphere_covering_var...,cluster_tai00400_020_2_0,400,20,2,0,1,7795.846059,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
17,radius,llm_selected,03_20260518_181812_candidate_004_hybrid_sampli...,cluster_tai00400_020_2_0,400,20,2,0,1,9478.000000,...,1.397111,1.397111,1.397111,1.397111,1,1,0,0,1.0,0.0
18,radius,llm_selected,03_candidate_004_sampling_50p_full_valid,cluster_tai00400_020_2_0,400,20,2,0,1,8874.598197,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
19,radius,llm_selected,04_20260518_181812_candidate_006_hybrid_sampli...,cluster_tai00400_020_2_0,400,20,2,0,1,10772.000000,...,1.587854,1.587854,1.587854,1.587854,1,1,0,0,1.0,0.0
20,radius,llm_selected,04_candidate_007_sampling_50p_best_gap,cluster_tai00400_020_2_0,400,20,2,0,1,9488.426107,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
21,radius,llm_selected,05_20260518_162854_candidate_020_fast_sample_b...,cluster_tai00400_020_2_0,400,20,2,0,1,9702.000000,...,1.430130,1.430130,1.430130,1.430130,1,1,0,0,1.0,0.0
22,radius,llm_selected,05_candidate_008_sampling_20p_fast_broad,cluster_tai00400_020_2_0,400,20,2,0,1,8670.378450,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
23,radius,llm_selected,06_20260517_191550_candidate_014_cluster_split...,cluster_tai00400_020_2_0,400,20,2,0,1,15986.000000,...,2.356427,2.356427,2.356427,2.356427,1,1,0,0,1.0,0.0
24,radius,llm_selected,06_VolumeCovering_V5,cluster_tai00400_020_2_0,400,20,2,0,1,11296.163930,...,NaN,NaN,NaN,NaN,1,1,0,0,1.0,0.0
25,radius,llm_selected,07_20260518_080147_candidate_008_dynamic_radiu...,cluster_tai00400_020_2_0,400,20,2,0,1,14907.000000,...,2.197376,2.197376,2.197376,2.197376,1,1,0,0,1.0,0.0
26,radius,taillard_cpp,taillard_cpp_hybrid_10p,cluster_tai00400_020_2_0,400,20,2,0,30,8213.490560,...,1.210715,1.251169,1.105465,1.469369,30,30,0,0,1.0,0.0
27,radius,taillard_cpp,taillard_cpp_kmedian,cluster_tai00400_020_2_0,400,20,2,0,30,10786.017280,...,1.589920,1.579388,1.299882,1.834154,30,30,0,0,1.0,0.0
28,radius,taillard_cpp,taillard_cpp_pam,cluster_tai00400_020_2_0,400,20,2,0,30,8245.985920,...,1.215505,1.223624,1.057183,1.398405,30,30,0,0,1.0,0.0
29,sse,external_baseline,sklearn_bisecting_kmeans,cluster_tai00400_020_2_0,400,20,2,0,30,70317.305484,...,NaN,NaN,NaN,NaN,30,30,0,0,1.0,0.0

 complexity_fit.csv -> OK
CSV exists but has no parseable columns. Usually means no data was available for this summary.

 complexity_fit_points.csv -> missing

 center_repair_warning_counts.json -> OK
{
  "snapped_to_points": 82
}

No complexity_plots directory yet.

Removing old zip: /content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1.zip

Creating artifact zip. This may take time for a large run...

Artifact zip: /content/drive/MyDrive/TM/final-clustering-evaluation/final_eval_smoke_clean_v1.zip
Zip exists: True
Zip size MB: 0.2

Starting browser download to your local PC...
If the zip is very large, the download may take a while or the browser may ask for confirmation.

Download command sent to browser.